#!/usr/bin/env python3
"""gen_itemcodes.py - the item codes $GETJPI and $GETSYI know (rd vms-bd30).

An item code a VMS program can pass is one STARLET defines: JPI$_* in $JPIDEF,
SYI$_* in $SYIDEF. A code that is not one of them is SS$_BADPARAM on OpenVMS
(observed: JPI.BADITEM / SYI.BADITEM, docs/oracle/semantics/info/); a defined
code OVMX does not answer is left unwritten, as VMS leaves an item it has no
value for. This generates src/libvms/include/ovmx_itemcodes.inc from the
STARLET definitions captured on OpenVMS Alpha V8.4 (docs/oracle/alpha84-starlet-
defs/{JPIDEF,SYIDEF}.txt). GENERATED -- never edit it; --check (a ctest) fails
when it is stale.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "src/libvms/include/ovmx_itemcodes.inc")


def codes(fac):
    path = os.path.join(ROOT, "docs/oracle/alpha84-starlet-defs/%sDEF.txt" % fac)
    out = set()
    for ln in open(path, errors="ignore"):
        m = re.match(r"\$EQU\s+%s\$_(\w+)\s+(\d+)\s*$" % fac, ln)
        if m and not m.group(1).startswith(("LAST", "FIRST")):
            out.add(int(m.group(2)))
    return sorted(out)


def build():
    lines = ["/* GENERATED by tools/oracle/gen_itemcodes.py from docs/oracle/alpha84-starlet-defs/",
             " * {JPIDEF,SYIDEF}.txt -- the item codes OpenVMS defines. DO NOT EDIT. */"]
    for fac in ("JPI", "SYI"):
        c = codes(fac)
        lines.append("static const uint32_t ovmx_%s_items[%d] = {" % (fac.lower(), len(c)))
        for i in range(0, len(c), 10):
            lines.append("    " + ", ".join("%d" % x for x in c[i:i + 10]) + ",")
        lines.append("};")
    return "\n".join(lines) + "\n"


def main(argv):
    text = build()
    if "--check" in argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("FAIL: %s is stale -- run tools/oracle/gen_itemcodes.py" % OUT)
            return 1
        print("OK: %s is current" % OUT)
        return 0
    open(OUT, "w").write(text)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
