#!/bin/sh
# mk_tcc.sh — build recipe for TCC.EXE, tinycc (third-party/tcc) built AS a
# VMS-native EXECUTABLE image (bead vms-4ba.4, epic vms-4ba "self-host S2: a C
# compiler as an OVMX image"). Mirrors mk_dcl.sh exactly: compile every TU
# with the proven freestanding musl CFLAGS, then LINK.EXE --executable --use
# {DECC$SHR + the five OVMX shareables} -o TCC.EXE.
#
# RMS FILE I/O (vms-4ba.5): TCC.EXE's own primary-source-file read and
# output-object write are routed through OVMX's RMS system services
# (sys$open/$connect/$get to read, sys$create/$connect/$put/$close to write)
# instead of talking to DECC$SHR's raw open()/read()/write() for those two
# files. This is a small, clearly-labeled OVMX addition: a new companion TU
# (third-party/tcc/ovmx/ovmx_rms_io.c, added to OBJS below) plus three
# `#ifdef OVMX_RMS_IO` seams in the otherwise-stock vendored tcc source
# (libtcc.c's tcc_add_file_internal/tcc_close, tccpp.c's handle_eob,
# tccelf.c's tcc_write_elf_file) — every edit is tagged "OVMX (vms-4ba.5)" in
# the vendored files themselves so a diff against upstream tinycc stays
# self-documenting. See ovmx_rms_io.h for exactly what is and is not routed
# through RMS (header/#include search is deliberately left on the stock path).
#
# COMPOSITION: tinycc's NATIVE (non-cross, non-ONE_SOURCE) build shape — the same
# shape `third-party/tcc/Makefile`'s `make tcc` produces via stock ./configure &&
# make (config.mak has no ONE_SOURCE=yes, so the standard multi-TU split applies):
#   tcc.c     (+ #include "tcctools.c", unconditional) -DONE_SOURCE=0 -> thin CLI
#   libtcc.c                                            -DONE_SOURCE=0 -> public API
#   tccpp.c tccgen.c tccdbg.c tccasm.c tccelf.c tccrun.c              -> core
#   arm64-gen.c arm64-link.c arm64-asm.c                              -> arm64 backend
# (-DONE_SOURCE=0 on tcc.c/libtcc.c only: without it each would #include the six
# core .c files again itself, since both carry the same
# `#ifndef ONE_SOURCE #define ONE_SOURCE 1 #endif / #if ONE_SOURCE #include ...`
# guard — omitting the define on tcc.o/libtcc.o duplicate-defines every core
# symbol against the separately-compiled tccpp.o/tccgen.o/etc.)
# 11 objects total, zero __thread anywhere in tcc's OWN source (the only
# `__thread` hit is tccgen.c's TOK___thread — tcc's lexer recognizing the *input*
# C keyword, not a TLS variable of tcc's own) — so the "one TLS-defining TU per
# image" constraint is trivially satisfied: TCC.EXE carries NO PT_TLS at all.
#
# Two build-time-only codegen artifacts (never become part of the final image,
# so compiled with plain host $CC, no freestanding flags):
#   config.h      — generated by tinycc's own ./configure (auto-detects
#                   TCC_TARGET_ARM64 from the compiler's __aarch64__ predefine;
#                   no cross DEF-arm64 needed for a native build)
#   tccdefs_.h    — c2str.exe (built with `$CC -DC2STR conftest.c`) converts
#                   include/tccdefs.h into the C-string table tccpp.c #includes
#                   for its built-in preprocessor predefines
# Both land in WORK and are found via -I$WORK when compiling tcc's real TUs.
#
# DECC$SHR EXTENSION (vms-4ba.4): tcc references 39 more PROCEDURE universals
# no prior consumer needed — 18 libgcc IEEE-quad (`long double`) soft-float
# helpers + __clear_cache (libgcc.a is already whole-archived into DECC$SHR but
# those were kept internal-only; tcc's own long-double constant folding + arm64
# JIT icache flush need them as real cross-image imports) plus 20 musl libc
# calls (dlopen/dlsym/dlclose, fdopen, ldexpl, longjmp/setjmp, mprotect, remove,
# sem_*, sigaddset/sigprocmask, strpbrk, strtof/strtold/strtoull, atoi,
# __assert_fail). See mk_decc_shr.sh's vms-4ba.4 comment block for the full
# enumeration method. DECC$SHR.EXE (built by mk_decc_shr.sh) MUST be rebuilt
# with these before this script's LINK.EXE step will resolve cleanly.
#
# --allow-undefined (ONE deferred import: `environ`) — NOT a hack around a
# missing libc feature. `environ` is tcc's only OTHER cross-image reference
# (tccrun.c's `-run` JIT execve-argv-passthrough path — dead code for `tcc -c`,
# the only mode this bead's DONE conditions exercise). It is deliberately NOT a
# DECC$SHR universal: exporting it hits a REAL LINK.EXE gap discovered while
# bringing up this bead — emit_shareable()'s universal-vector resolution runs
# BEFORE BSS section placement, so a BSS-bucket (uninitialized) DATA universal
# like musl's `environ` resolves its own placed address as 0 and LINK.EXE wrongly
# dies with "%LINK-F-ERROR, universal symbol not defined in any input object".
# link.c is out of Systems-Engineer file-domain for this bead (see the vms-4ba.4
# escalation / follow-up item) so it is NOT patched here; --allow-undefined is
# an existing, unmodified LINK.EXE flag (link.c:1772) that defers this ONE
# reference to a null import cell instead of failing the whole build — safe
# because `-run` never executes in our proof. Every OTHER external the 11 tcc
# objects reference is either intra-image or one of the 39 real universals
# above — this script's DONE-condition assertions below confirm no other
# symbol silently deferred.
#
# link.c and imgact.c are the complete toolchain and are OUT of the Systems-
# Engineer file-domain — do NOT edit them here.
#
# Usage:  mk_tcc.sh <LINK.EXE> <out-TCC.EXE> \
#             <DECC$SHR.EXE> <LIBVMS$SHR.EXE> <LIBVMSPROCESS$SHR.EXE> \
#             <LIBVMSFS$SHR.EXE> <LIBVMSLNM$SHR.EXE> <LIBVMSRMS$SHR.EXE> \
#             [tcc-src-dir]
# Env:    CC (default gcc)
# Must run in the arm64 musl container where the producer .EXE already exist
# (see epic vms-4ba's BUILD ENVIRONMENT section / CLAUDE.md test loop).
set -e

LINK_EXE=${1:?usage: mk_tcc.sh <LINK.EXE> <out> <DECC\$SHR> <LIBVMS\$SHR> <LIBVMSPROCESS\$SHR> <LIBVMSFS\$SHR> <LIBVMSLNM\$SHR> <LIBVMSRMS\$SHR> [tcc-src]}
OUT=${2:?need output TCC.EXE path}
DECC_SHR=${3:?need DECC\$SHR.EXE}
VMS_SHR=${4:?need LIBVMS\$SHR.EXE}
PROC_SHR=${5:?need LIBVMSPROCESS\$SHR.EXE}
FS_SHR=${6:?need LIBVMSFS\$SHR.EXE}
LNM_SHR=${7:?need LIBVMSLNM\$SHR.EXE}
RMS_SHR=${8:?need LIBVMSRMS\$SHR.EXE}
HERE=$(cd "$(dirname "$0")" && pwd)                                   # src/vmslink
TCC_SRC=${9:-$(cd "$HERE/../../third-party/tcc/src" && pwd)}          # third-party/tcc/src
OVMX_DIR=$(cd "$HERE/../../third-party/tcc/ovmx" && pwd)              # third-party/tcc/ovmx (vms-4ba.5 shim)
VMSRMS_INC=$(cd "$HERE/../vmsrms/include" && pwd)                     # rms/{fab,rab,rms}.h
LIBVMS_INC=$(cd "$HERE/../libvms/include" && pwd)                     # rmsdef.h/ssdef.h (rms.h deps)
CC=${CC:-gcc}

for f in "$DECC_SHR" "$VMS_SHR" "$PROC_SHR" "$FS_SHR" "$LNM_SHR" "$RMS_SHR"; do
    [ -f "$f" ] || { echo "mk_tcc: producer image not found: $f"; exit 1; }
done
[ -d "$TCC_SRC" ] || { echo "mk_tcc: tcc src dir not found: $TCC_SRC"; exit 1; }
[ -d "$OVMX_DIR" ] || { echo "mk_tcc: OVMX shim dir not found: $OVMX_DIR"; exit 1; }

WORK=${WORK:-/tmp/mk-tcc}
rm -rf "$WORK"
mkdir -p "$WORK"

echo "mk_tcc: ./configure (host tool, generates config.h; writes to CWD, so cd \$WORK first)"
( cd "$WORK" && sh "$TCC_SRC/configure" --source-path="$TCC_SRC" --cc="$CC" ) >"$WORK/configure.log" 2>&1 \
    || { echo "mk_tcc: configure failed, see $WORK/configure.log"; tail -20 "$WORK/configure.log"; exit 1; }
[ -f "$WORK/config.h" ] || { echo "mk_tcc: configure did not produce config.h"; exit 1; }

echo "mk_tcc: c2str.exe + tccdefs_.h (host tools, generate the predefs table)"
$CC -DC2STR "$TCC_SRC/conftest.c" -o "$WORK/c2str.exe"
"$WORK/c2str.exe" "$TCC_SRC/include/tccdefs.h" "$WORK/tccdefs_.h"
[ -f "$WORK/tccdefs_.h" ] || { echo "mk_tcc: c2str did not produce tccdefs_.h"; exit 1; }

CFLAGS="-fPIC -O2 -ffreestanding -fno-builtin -fno-stack-protector -mno-outline-atomics"
# -DOVMX_RMS_IO (vms-4ba.5): activates the three #ifdef seams in
# libtcc.c/tccpp.c/tccelf.c that route tcc's primary-source read + object
# write through RMS instead of raw open()/read()/write(). Applied uniformly
# to every TU below — harmless no-op for the TUs that don't reference it.
# -DOVMX_DATA_RO_WRITABLE (vms-4ba.6): makes tcc emit its .data.ro
# pointer-initializer section (tcc_options[] et al.) with SHF_WRITE, so
# LINK.EXE resolves the ABS64 pointer relocations it carries — see the
# OVMX seam in third-party/tcc/src/tccelf.c (shf_RELRO). REQUIRED for a
# self-hosted TCC.EXE (gen-2, tcc-compiled): without it every .data.ro
# pointer lands NULL and the second-generation tcc matches no CLI option.
# Only affects tccelf.c's section creation; a no-op for TUs that never
# emit relocatable rodata.
DEFS="-D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -DOVMX_RMS_IO -DOVMX_DATA_RO_WRITABLE"
INCS="-I$WORK -I$TCC_SRC -I$OVMX_DIR"

# Core TUs (compiled as-is — no ONE_SOURCE define, so each is its own real TU).
CORE_TUS="tccpp tccgen tccdbg tccasm tccelf tccrun arm64-gen arm64-link arm64-asm"
# tcc.c and libtcc.c BOTH need -DONE_SOURCE=0 (see header comment) — kept
# separate from CORE_TUS since they take an extra define the others don't.
WRAPPER_TUS="tcc libtcc"

OBJS=""
for t in $CORE_TUS; do
    echo "  cc $t.c"
    $CC $CFLAGS $DEFS $INCS -c -o "$WORK/$t.o" "$TCC_SRC/$t.c"
    OBJS="$OBJS $WORK/$t.o"
done
for t in $WRAPPER_TUS; do
    echo "  cc $t.c (ONE_SOURCE=0)"
    $CC $CFLAGS $DEFS -DONE_SOURCE=0 $INCS -c -o "$WORK/$t.o" "$TCC_SRC/$t.c"
    OBJS="$OBJS $WORK/$t.o"
done

# 12th object (vms-4ba.5): the OVMX RMS I/O shim itself. Needs rms/rms.h in
# addition to the standard INCS.
echo "  cc ovmx_rms_io.c (vms-4ba.5 RMS I/O shim)"
$CC $CFLAGS $DEFS $INCS -I"$VMSRMS_INC" -I"$LIBVMS_INC" -c -o "$WORK/ovmx_rms_io.o" "$OVMX_DIR/ovmx_rms_io.c"
OBJS="$OBJS $WORK/ovmx_rms_io.o"

NOBJ=$(echo $OBJS | wc -w)
echo "mk_tcc: $NOBJ tcc objects compiled VMS-native-clean"
[ "$NOBJ" -eq 12 ] || { echo "mk_tcc: FAIL: expected 12 tcc objects (11 stock + ovmx_rms_io.o), got $NOBJ"; exit 1; }

echo "mk_tcc: LINK.EXE --executable --use {6 producers} --allow-undefined (environ only) -> $OUT"
# --allow-undefined: see the header comment — defers ONLY tcc's dead-for-`-c`
# `environ` reference (tccrun.c `-run` path); every other external must still
# bind or LINK.EXE dies (this script does not otherwise weaken the link).
# shellcheck disable=SC2086
LINK_ERR="$WORK/tcc-link.err"
"$LINK_EXE" --executable --allow-undefined \
    --use "$DECC_SHR" --use "$VMS_SHR" --use "$PROC_SHR" \
    --use "$FS_SHR" --use "$LNM_SHR" --use "$RMS_SHR" \
    -o "$OUT" $OBJS 2>"$LINK_ERR"
LRC=$?
cat "$LINK_ERR" >&2
[ "$LRC" -eq 0 ] || { echo "mk_tcc: FAIL: LINK.EXE --executable exited $LRC"; exit 1; }

# Guard against a SILENT extra deferral: LINK.EXE prints "%LINK-I-DEFEXT, N
# external reference(s) left unresolved" (link.c:1725) when --allow-undefined
# deferred anything. Confirm N is exactly 1 (environ) — if some OTHER symbol
# also went unresolved (e.g. a DECC$SHR export got dropped), N climbs above 1
# and this catches it instead of shipping a TCC.EXE with a silently-broken
# import. Zero deferrals (no DEFEXT line at all) would also be wrong: it means
# environ resolved some other way and this comment/guard is stale.
NDEFER=$(grep -oE 'LINK-I-DEFEXT, [0-9]+' "$LINK_ERR" | grep -oE '[0-9]+')
if [ "${NDEFER:-0}" -ne 1 ]; then
    echo "mk_tcc: FAIL: expected exactly 1 deferred import (environ), LINK.EXE reported ${NDEFER:-0}"
    exit 1
fi
echo "mk_tcc: confirmed exactly 1 deferred import (environ, dead code for tcc -c)"

echo "mk_tcc: created $OUT"
