#!/usr/bin/env python3
"""gen_atrdef.py -- generate src/libvms/include/vms/atrdef.h (vms-38b) from the
oracle capture docs/oracle/alpha84-starlet-defs/ATRDEF.txt: the ACP attribute
codes (ATR$C_*) and sizes (ATR$S_*) printed by a live OpenVMS Alpha V8.4 node's
own STARLET.MLB, plus the attribute-list item (ATR$W_SIZE / ATR$W_TYPE /
ATR$L_ADDR at the captured offsets). Never hand-edit the header: re-run this.

  gen_atrdef.py            write the header
  gen_atrdef.py --check    exit 1 if the committed header differs from the output
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = os.path.join(ROOT, "docs/oracle/alpha84-starlet-defs/ATRDEF.txt")
OUT = os.path.join(ROOT, "src/libvms/include/vms/atrdef.h")


def load():
    d = []
    for ln in open(SRC):
        m = re.match(r"\$EQU\s+(ATR\$[A-Z0-9_$]+)\s+(-?\d+)\s*$", ln)
        if m:
            d.append((m.group(1), int(m.group(2))))
    return d


def render(defs):
    v = dict(defs)
    for k, want in (("ATR$W_SIZE", 0), ("ATR$W_TYPE", 2), ("ATR$L_ADDR", 4)):
        if v.get(k) != want:
            raise SystemExit("gen_atrdef: %s is %r in the capture, the item layout below assumes %d" % (k, v.get(k), want))
    out = ["/*",
           " * vms/atrdef.h - ACP attribute codes and the attribute-list item (vms-38b).",
           " * GENERATED by tools/cross-alpha-vms/include-surface/gen_atrdef.py from",
           " * docs/oracle/alpha84-starlet-defs/ATRDEF.txt (OpenVMS Alpha V8.4 STARLET.MLB,",
           " * observed). Do not edit: re-run the generator.",
           " */",
           "#ifndef __VMS_ATRDEF_H",
           "#define __VMS_ATRDEF_H",
           '#include "vms_abi.h"',
           ""]
    for name, val in defs:
        if re.match(r"ATR\$[CS]_", name):
            out.append("#define %-32s %d" % (name, val))
    out += ["",
            "#pragma __required_pointer_size __save",
            "#pragma __required_pointer_size __short",
            "",
            "/* One attribute-list entry (ATR$W_SIZE 0, ATR$W_TYPE 2, ATR$L_ADDR 4); a list",
            " * is ended by an entry whose size and type are 0. */",
            "typedef struct atrdef {",
            "    unsigned short atr$w_size;",
            "    unsigned short atr$w_type;",
            "    void          *atr$l_addr;",
            "} ATRDEF;",
            "",
            "#pragma __required_pointer_size __restore",
            "",
            "__VMS_ABI_SIZE(struct atrdef, 8);",
            "__VMS_ABI_OFFSET(struct atrdef, atr$w_type, 2);",
            "__VMS_ABI_OFFSET(struct atrdef, atr$l_addr, 4);",
            "",
            "#endif /* __VMS_ATRDEF_H */",
            ""]
    return "\n".join(out)


def main(argv):
    text = render(load())
    if "--check" in argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("gen_atrdef: %s is not the generator's output -- re-run gen_atrdef.py" % OUT, file=sys.stderr)
            return 1
        return 0
    open(OUT, "w").write(text)
    print("gen_atrdef: wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
