#!/bin/sh
# build-vmsfs-core-vax.sh - cross-compile the substrate-neutral ODS-2 core
# (src/kernel-core/vmsfs/*.c) for elf32-vax and prove it is ILP32/endian-clean
# (rd vms-bb8, epic vms-8e8; the ODS-2 analog of build-libvmssys-vax.sh).
#
# Runs INSIDE the ovmx-cross-vax container (tools/cross-vax/Dockerfile), which
# provides the pinned vax--netbsdelf gcc/binutils. Nothing here touches the host.
#
# This is a FREESTANDING, KERNEL-STYLE compile: the ODS-2 core is kernel
# filesystem code, so it is built with -ffreestanding -fno-builtin -nostdinc and
# NO libc / NO NetBSD sysroot -- only the compiler's own fixed-width headers and
# the freestanding WIDTH-AUDIT backend (vmsfs_backend_audit.h, selected by
# -DOVMX_KBACKEND_AUDIT). The core reaches its block I/O through extern ops with
# no bodies, so it compiles to RELOCATABLE OBJECTS (`gcc -c`); it is never linked
# into a runnable image (there is no VAX system emulator here -- a booted-volume
# round-trip is the later SIMH/V5 phase). BUILD/TEST TOOLING, never a runtime
# (Rule 9): the audit binds no VFS and mounts nothing.
#
# The proof is threefold and all at compile time under the 32-bit VAX compiler:
#   1. every ODS-2 core .c compiles -Werror for elf32-vax (any long/pointer-width
#      assumption in the allocator / dir-scanner / header / map math is a hard
#      error);
#   2. vmsfs_ondisk.h's _Static_asserts (512/512/88/8-byte on-disk structs) and
#      vmsfs_width_audit.c's explicit width + offset asserts pass under ILP32;
#   3. every emitted object is verified `file format elf32-vax` (arch: vax).
#
# Exit 0 = all objects built clean for elf32-vax. Any failure is fatal (set -e).

set -eu

TARGET="${TARGET:-vax--netbsdelf}"
CC="${TARGET}-gcc"
AR="${TARGET}-ar"
OBJDUMP="${TARGET}-objdump"
SRC="$(pwd)"
CORE="$SRC/src/kernel-core/vmsfs"
ONDISK_DIR="$SRC/src/kernel/vmsfs"          # vmsfs_ondisk.h lives beside the Linux glue
AUDIT_DIR="$SRC/tools/cross-vax"            # the freestanding width-audit backend
OUT="${OUT:-/tmp/vmsfs-core-vax}"
rm -rf "$OUT"; mkdir -p "$OUT"

# Kernel-style freestanding flags: -ffreestanding -fno-builtin means no libc
# code and no compiler builtins are assumed. The core still needs the ABI's
# FIXED-WIDTH TYPE headers (<stdint.h>/<stddef.h>/<stdbool.h>); on this
# NetBSD-targeted gcc even the compiler's own stddef.h pulls <machine/ansi.h>
# from the sysroot, so a hard -nostdinc is not viable. We therefore let the
# pinned NetBSD/vax sysroot supply ONLY those type headers (they define
# uint32_t/size_t/... at the correct ILP32 widths -- exactly what the width audit
# wants) and pull NO libc FUNCTION: the string/ctype vocabulary is declared by
# vmsfs_backend_audit.h and left unresolved (compile-to-object).
SYSROOT="${SYSROOT:-/opt/cross/sysroot}"
CFLAGS="-ffreestanding -fno-builtin --sysroot=$SYSROOT -std=gnu11 -O2 -Wall -Werror"
CPPFLAGS="-DOVMX_KBACKEND_AUDIT -I$CORE -I$ONDISK_DIR -I$AUDIT_DIR"

echo "=== toolchain ==="
"$CC" --version | head -1
"$CC" -dumpmachine
echo

echo "=== the ODS-2 core translation units under audit ==="
CORE_SRCS="vmsfs_version.c vmsfs_map.c vmsfs_name.c vmsfs_alloc.c vmsfs_dirscan.c vmsfs_header.c"
for c in $CORE_SRCS; do
    test -f "$CORE/$c" || { echo "FAIL: missing core source $CORE/$c"; exit 1; }
    echo "  src/kernel-core/vmsfs/$c"
done
echo "  (generated) vmsfs_width_audit.c   (explicit width + offset asserts)"
echo

echo "=== compile each core TU freestanding for elf32-vax (-Werror) ==="
OBJS=""
for c in $CORE_SRCS; do
    o="$OUT/${c%.c}.o"
    echo "--- $CC -c src/kernel-core/vmsfs/$c ---"
    # shellcheck disable=SC2086
    "$CC" $CFLAGS $CPPFLAGS -c "$CORE/$c" -o "$o"
    OBJS="$OBJS $o"
done
# The explicit width-audit TU (ILP32 + on-disk layout _Static_asserts). It is
# GENERATED here at runtime rather than committed as a .c under tools/, exactly
# as build-libvmssys-vax.sh generates its width.c/smoke.c: a committed VAX-only,
# freestanding .c under src/ or tools/ is host-compiled by the authenticity
# gate tests/integration/test_userspace_service_register.sh (which globs every
# product .c), where it cannot build (it resolves to the Linux <linux/...>
# backend on the host) -- so it must not exist as a repo file.
WIDTH_TU="$OUT/vmsfs_width_audit.c"
cat > "$WIDTH_TU" <<'WIDTH_EOF'
/* GENERATED by build-vmsfs-core-vax.sh -- the explicit ILP32/endian width proof
 * for the OVMX ODS-2 core, compiled for elf32-vax (rd vms-bb8, epic vms-8e8).
 * Includes the whole core contract and asserts, at compile time under the 32-bit
 * VAX compiler, the width class + the on-disk struct sizes/offsets + the in-core
 * POD carrier widths + the 64-bit wall-clock contract. See
 * docs/audit-ilp32-vax-vmsfs.md sec 1-3. Not committed (see the build script). */
#include "vmsfs_bio.h"    /* -> vmsfs_core.h -> vmsfs_ondisk.h + the POD seam */

/* 1. width class: this must be the 32-bit ILP32 VAX, not an LP64 host */
_Static_assert(sizeof(long)      == 4, "VAX long must be 32-bit (ILP32)");
_Static_assert(sizeof(void *)    == 4, "VAX pointer must be 32-bit (ILP32)");
_Static_assert(sizeof(int)       == 4, "int 32-bit");
_Static_assert(sizeof(long long) == 8, "long long 64-bit");
_Static_assert(sizeof(size_t)    == sizeof(void *), "size_t tracks pointer width");

/* 2. on-disk format: identical size on ILP32 (fixed-width fields only) */
_Static_assert(sizeof(struct vmsfs_retrieval_ptr) == 8,   "retrieval ptr 8 bytes");
_Static_assert(sizeof(struct vmsfs_home_block)    == 512, "home block 512 bytes");
_Static_assert(sizeof(struct vmsfs_file_header)   == 512, "file header 512 bytes");
_Static_assert(sizeof(struct vmsfs_dir_entry)     == 88,  "dir entry 88 bytes");

/* field OFFSETS must be identical on ILP32 too (a long/pointer field would shift them) */
_Static_assert(offsetof(struct vmsfs_file_header, fh_size)     == 8,   "fh_size @8");
_Static_assert(offsetof(struct vmsfs_file_header, fh_created)  == 16,  "fh_created @16");
_Static_assert(offsetof(struct vmsfs_file_header, fh_map)      == 152, "fh_map @152");
_Static_assert(offsetof(struct vmsfs_file_header, fh_checksum) == 508, "fh_checksum @508");
_Static_assert(offsetof(struct vmsfs_home_block,  hb_modified) == 16,  "hb_modified @16");
_Static_assert(offsetof(struct vmsfs_home_block,  hb_checksum) == 508, "hb_checksum @508");
_Static_assert(offsetof(struct vmsfs_dir_entry,   de_name)     == 8,   "de_name @8");

/* 3. in-core POD carriers: fixed-width value fields, native pointers */
_Static_assert(sizeof(((struct vmsfs_fh_info *)0)->size)     == 8, "fh_info.size 64-bit");
_Static_assert(sizeof(((struct vmsfs_fh_info *)0)->created)  == 8, "fh_info.created 64-bit");
_Static_assert(sizeof(((struct vmsfs_fh_info *)0)->fid)      == 4, "fh_info.fid 32-bit");
_Static_assert(sizeof(((struct vmsfs_fh_meta *)0)->size)     == 8, "fh_meta.size 64-bit");

/* the 64-bit wall-clock contract the on-disk timestamps depend on */
_Static_assert(sizeof(vmsfs_now_seconds()) == 8,
	       "vmsfs_now_seconds() must be 64-bit or ODS-2 timestamps truncate on VAX");

const char vmsfs_width_audit_marker[] = "ovmx-vmsfs-core-elf32-vax-width-audit";
WIDTH_EOF
echo "--- $CC -c (generated) vmsfs_width_audit.c ---"
# shellcheck disable=SC2086
"$CC" $CFLAGS $CPPFLAGS -c "$WIDTH_TU" -o "$OUT/vmsfs_width_audit.o"
OBJS="$OBJS $OUT/vmsfs_width_audit.o"
echo

echo "=== archive the core objects (libvmsfs_core.a) ==="
"$AR" rcs "$OUT/libvmsfs_core.a" $OBJS
"$AR" t "$OUT/libvmsfs_core.a"
echo

echo "=== assert every emitted object is elf32-vax (arch: vax) ==="
FAIL=0
for o in $OBJS; do
    FMT="$("$OBJDUMP" -f "$o" | grep -Ei 'file format|architecture' | tr '\n' ' ')"
    echo "  $(basename "$o"): $FMT"
    echo "$FMT" | grep -qiF 'file format elf32-vax' || { echo "    ^ NOT elf32-vax"; FAIL=1; }
    echo "$FMT" | grep -qiE 'architecture: *vax' || { echo "    ^ arch not vax"; FAIL=1; }
done
[ "$FAIL" -eq 0 ] || { echo "FAIL: at least one object was not elf32-vax/vax"; exit 1; }
echo

echo "=== ALL PROOFS PASSED: vmsfs-core compiles for elf32-vax (ILP32 width-clean) ==="
