/* SPDX-License-Identifier: GPL-2.0 */
/*
 * vmsfs_backend_audit.h - the FREESTANDING WIDTH-AUDIT backend for the OVMX
 * ODS-2 core (rd vms-bb8, epic vms-8e8).
 *
 * This realizes the vmsfs_backend.h + vmsfs_bio.h vocabulary contract with the
 * MINIMUM needed to COMPILE the substrate-neutral ODS-2 core
 * (the ODS-2 core .c files) for a new architecture and width class -- here,
 * elf32-vax (32-bit little-endian, ILP32). It is selected by
 * -DOVMX_KBACKEND_AUDIT and used only by tools/cross-vax/build-vmsfs-core-vax.sh
 * / the CI job "vmsfs-core cross-compiles for elf32-vax".
 *
 * WHAT THIS IS NOT (Rule 9 -- BUILD/TEST TOOLING, never a runtime): it binds no
 * VFS, mounts no volume, and does NO real block I/O. The block-buffer ops
 * (vmsfs_bget/bdata/bdirty/bput) and the bitmap ops are declared as EXTERN
 * prototypes with no bodies -- the audit compiles the core to relocatable
 * objects (`gcc -c`), never links a runnable image, so leaving these unresolved
 * is correct and deliberate. Providing fake success bodies here would be exactly
 * the silent-userspace-fallback LARP the authenticity invariants forbid. The
 * REAL realizations live in each shipping backend: vmsfs_backend_linux.h today,
 * a NetBSD vnode backend (rd vms-308, phase V4) later.
 *
 * Why the audit build is a legitimate width proof even though it does not run:
 *   1. It forces the ENTIRE ODS-2 core through a 32-bit ILP32 compiler, so any
 *      `long`/pointer-width assumption in the allocator / dir-scanner / header
 *      / map math is a hard compile error, not a latent runtime bug.
 *   2. vmsfs_ondisk.h's _Static_asserts (512-byte home block / file header,
 *      88-byte dir entry, 8-byte retrieval pointer) are re-evaluated under
 *      ILP32 -- if any on-disk field silently resized, the build fails.
 *   3. The width TU (generated by build-vmsfs-core-vax.sh) pins
 *      sizeof(long)==4 / sizeof(void*)==4
 *      so the proof cannot pass on an LP64 host by accident.
 *
 * Endianness: VAX is little-endian, exactly like every other OVMX target, so the
 * le<->cpu ops below are identities that keep the fixed WIDTH exact. They are
 * written as pure functions over fixed-width types; no host header, no byte
 * order assumed beyond "target is LE" (which the VAX is). A big-endian port
 * would supply real byte-swapping ops here instead -- the core would not change.
 *
 * Clean-room (CLAUDE.md Rule 8): OVMX's own code over the standard freestanding
 * type/string/ctype vocabulary. No VSI/HPE/Linux/NetBSD source is copied.
 */

#ifndef OVMX_VMSFS_BACKEND_AUDIT_H
#define OVMX_VMSFS_BACKEND_AUDIT_H

/*
 * Fixed-width + size + bool TYPE vocabulary only. These pull the ABI's
 * fixed-width type definitions (uint32_t/size_t/bool at their correct ILP32
 * widths on VAX) and NO libc function -- the string/ctype vocabulary below is
 * declared by hand and left unresolved. -ffreestanding -fno-builtin keeps the
 * compile kernel-style (no libc code, no builtins assumed).
 */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* ================================================================
 * Error codes (normalized ODS-2-core spelling). Concrete values are the audit's
 * own small integers -- the core only ever returns their NEGATION and compares
 * for equality, so any distinct non-zero set proves the compile; a shipping
 * backend maps each to its host errno.
 * ================================================================ */
#define VMSFS_EINVAL        22   /* invalid argument / unparseable filespec   */
#define VMSFS_ENAMETOOLONG  36   /* name does not fit the caller's buffer      */
#define VMSFS_EIO           5    /* VBN not mapped / block I/O error           */
#define VMSFS_ENOSPC        28   /* retrieval-ptr array full / no free block   */
#define VMSFS_ENOENT        2    /* directory entry / file header not found    */

/* ================================================================
 * String / ctype / memory vocabulary the core calls by ordinary names. Declared
 * as prototypes only: the core compiles to relocatable objects, so these stay
 * unresolved (a shipping backend binds them to its host primitives). strscpy is
 * the bounded, always-NUL-terminating copy; the core uses only its truncating
 * effect, never the return value.
 * ================================================================ */
void   *memcpy(void *dest, const void *src, size_t n);
void   *memset(void *s, int c, size_t n);
int     memcmp(const void *a, const void *b, size_t n);
size_t  strlen(const char *s);
char   *strchr(const char *s, int c);
char   *strrchr(const char *s, int c);
int     strncasecmp(const char *a, const char *b, size_t n);
long    strscpy(char *dest, const char *src, size_t count);
int     snprintf(char *buf, size_t size, const char *fmt, ...);
int     isdigit(int c);
int     toupper(int c);

/* ================================================================
 * Endian access. VAX is little-endian: identity that keeps the WIDTH exact.
 * ================================================================ */
static inline uint16_t vmsfs_le16_to_cpu(uint16_t v) { return v; }
static inline uint32_t vmsfs_le32_to_cpu(uint32_t v) { return v; }
static inline uint64_t vmsfs_le64_to_cpu(uint64_t v) { return v; }
static inline uint16_t vmsfs_cpu_to_le16(uint16_t v) { return v; }
static inline uint32_t vmsfs_cpu_to_le32(uint32_t v) { return v; }
static inline uint64_t vmsfs_cpu_to_le64(uint64_t v) { return v; }

/* ================================================================
 * Wall clock. WIDTH-CRITICAL CONTRACT: this MUST return a 64-bit type. The core
 * feeds it straight into vmsfs_cpu_to_le64() for the 64-bit on-disk timestamps
 * (fh_created/modified/... , hb_modified). If a backend declared it returning a
 * 32-bit `time_t` (as some 32-bit hosts still do), the value would truncate
 * BEFORE the le64 store on ILP32 -- a Y2038 defect that never shows on LP64.
 * Pinned to int64_t here so the whole core is type-checked against that width;
 * Linux's ktime_get_real_seconds() (time64_t) already satisfies it. Returns 0 in
 * the audit (no runtime).
 * ================================================================ */
static inline int64_t vmsfs_now_seconds(void) { return 0; }

/* ================================================================
 * Storage-bitmap ops. The on-disk bitmap is a bit array; each backend caches it
 * in memory as an `unsigned long` word array and locates bits by index. The
 * core passes only uint32_t bit indices -- it never indexes the words itself --
 * so the word WIDTH (32-bit on VAX ILP32, 64-bit on LP64) is a pure in-memory
 * backend representation and, because VAX is LE, is byte-order-safe. Extern
 * prototypes; unresolved in the relocatable-object audit.
 * ================================================================ */
uint32_t vmsfs_bit_find_zero(const unsigned long *bitmap, uint32_t nbits,
			     uint32_t start);
void     vmsfs_bit_set(unsigned long *bitmap, uint32_t bit);
void     vmsfs_bit_clear(unsigned long *bitmap, uint32_t bit);
int      vmsfs_bit_test(const unsigned long *bitmap, uint32_t bit);

/* ================================================================
 * Block-buffer ops (the sb_bread / brelse equivalent). Extern prototypes;
 * unresolved in the audit -- the real block I/O is the shipping backend's.
 * `host` is the opaque backend volume handle from struct vmsfs_volume.
 * ================================================================ */
struct vmsfs_bh;
struct vmsfs_bh *vmsfs_bget(void *host, uint32_t lbn);
void            *vmsfs_bdata(struct vmsfs_bh *bh);
void             vmsfs_bdirty(struct vmsfs_bh *bh);
void             vmsfs_bdirty_sync(struct vmsfs_bh *bh);
void             vmsfs_bput(struct vmsfs_bh *bh);

#endif /* OVMX_VMSFS_BACKEND_AUDIT_H */
