/*
 * NSADEF.H - VMS Security Audit (NSA$) Item Codes and Constants
 *
 * OpenVMX compatibility layer - Defines the NSA$_ item codes used
 * with sys$audit_eventw, and the NSA$C_/NSA$M_ constants used with
 * sys$format_audit and sys$audit_eventw.
 *
 * PROVENANCE: the item-list mechanism and general purpose of these
 * symbols are documented in the public OpenVMS Guide to System
 * Security / System Services Reference Manual ($AUDIT_EVENT,
 * $FORMAT_AUDIT). Exact numeric values could NOT be confirmed against
 * a fetchable public source in this session — sequential OVMX
 * assignment (clean-room, CLAUDE.md rule 8), matching the numbering
 * style already used elsewhere in this tree (e.g. dvidef.h). Flagged
 * in vms-531 findings for operator sign-off.
 *
 * Reference: OpenVMS Guide to System Security
 *            OpenVMS System Services Reference Manual ($AUDIT_EVENT,
 *            $FORMAT_AUDIT)
 */

#ifndef __NSADEF_H
#define __NSADEF_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * VALUES ARE THE OBSERVED OpenVMS VAX V7.3 ONES (rd vms-f811): every number is
 * the $EQU value the lab node's own STARLET.MLB prints for $NSADEF
 * (docs/oracle/vax73-starlet-defs/NSADEF.txt). Only the groups OVMX uses are
 * reproduced here: NSA$_ item codes (packet types), NSA$M_/NSA$V_ audit flags,
 * NSA$C_MSG_ event classes, NSA$C_OBJ_ subtypes, NSA$C_FORMAT_STYLE_ and
 * NSA$C_VERSION_. The earlier revision of this header invented all of them.
 */

#define NSA$C_MSG_SERVER                   1
#define NSA$C_MSG_AUDIT                    2
#define NSA$C_MSG_BREAKIN                  3
#define NSA$C_MSG_INSTALL                  4
#define NSA$C_MSG_LOGFAIL                  5
#define NSA$C_MSG_LOGIN                    6
#define NSA$C_MSG_LOGOUT                   7
#define NSA$C_MSG_MOUNT                    8
#define NSA$C_MSG_NETPROXY                 9
#define NSA$C_MSG_ACCESS                   10
#define NSA$C_MSG_SYSUAF                   11
#define NSA$C_MSG_RIGHTSDB                 12
#define NSA$C_MSG_CUSTOMER                 13
#define NSA$C_MSG_CSS                      14
#define NSA$C_MSG_LP                       15
#define NSA$C_MSG_PRVAUD                   16
#define NSA$C_MSG_RESERVED_1               17
#define NSA$C_MSG_RESERVED_2               18
#define NSA$C_MSG_RESERVED_3               19
#define NSA$C_MSG_RESERVED_4               20
#define NSA$C_MSG_SYSTIME                  21
#define NSA$C_MSG_SYSGEN                   22
#define NSA$C_MSG_OBJ_CREATE               23
#define NSA$C_MSG_OBJ_DELETE               24
#define NSA$C_MSG_OBJ_DEACCESS             25
#define NSA$C_MSG_OBJ_ACCESS               26
#define NSA$C_MSG_CONNECTION               27
#define NSA$C_MSG_RESERVED_5               28
#define NSA$C_MSG_NCP                      29
#define NSA$C_MSG_PROCESS                  30
#define NSA$C_MSG_OBJECT_SERVICE           31
#define NSA$C_MSG_AUTHENTICATE             32
#define NSA$C_MSG_MAX_CODE                 33
#define NSA$M_MANDATORY                    1
#define NSA$M_ACL                          2
#define NSA$M_INTERNAL                     4
#define NSA$M_ALARM                        8
#define NSA$M_AUDIT                        16
#define NSA$M_FOREIGN                      32
#define NSA$M_FLUSH                        64
#define NSA$M_SERVER                       128
#define NSA$M_DEACCESS                     256
#define NSA$M_SYNCH                        512
#define NSA$M_IDENTIFIER                   1024
#define NSA$M_PROCPRIV                     2048
#define NSA$M_AUTHPRIV                     4096
#define NSA$M_NOEVTCHECK                   8192
#define NSA$M_NOFAILAUD                    16384
#define NSA$M_NOSUCCAUD                    32768
#define NSA$C_VERSION_1                    1
#define NSA$C_VERSION_2                    2
#define NSA$C_VERSION_3                    3
#define NSA$C_MSG_HDR_LENGTH               20
#define NSA$V_MANDATORY                    0
#define NSA$V_ACL                          1
#define NSA$V_INTERNAL                     2
#define NSA$V_ALARM                        3
#define NSA$V_AUDIT                        4
#define NSA$V_FOREIGN                      5
#define NSA$V_FLUSH                        6
#define NSA$V_SERVER                       7
#define NSA$V_DEACCESS                     8
#define NSA$V_SYNCH                        9
#define NSA$V_IDENTIFIER                   10
#define NSA$V_PROCPRIV                     11
#define NSA$V_AUTHPRIV                     12
#define NSA$V_NOEVTCHECK                   13
#define NSA$V_NOFAILAUD                    14
#define NSA$V_NOSUCCAUD                    15
#define NSA$M_INS_SPARE_0                  1
#define NSA$M_INS_OPEN                     2
#define NSA$M_INS_HEADER_RESIDENT          4
#define NSA$M_INS_SHARED                   8
#define NSA$M_INS_EXECUTE_ONLY             16
#define NSA$M_INS_WRITEABLE                32
#define NSA$M_INS_PRIVILEGED               64
#define NSA$M_INS_PROTECTED                128
#define NSA$M_INS_NOPURGE                  256
#define NSA$M_INS_ACCOUNTING               512
#define NSA$V_INS_SPARE_0                  0
#define NSA$V_INS_OPEN                     1
#define NSA$V_INS_HEADER_RESIDENT          2
#define NSA$V_INS_SHARED                   3
#define NSA$V_INS_EXECUTE_ONLY             4
#define NSA$V_INS_WRITEABLE                5
#define NSA$V_INS_PRIVILEGED               6
#define NSA$V_INS_PROTECTED                7
#define NSA$V_INS_NOPURGE                  8
#define NSA$V_INS_ACCOUNTING               9
#define NSA$M_MNT_FOREIGN                  1
#define NSA$M_MNT_GROUP                    2
#define NSA$M_MNT_NOASSIST                 4
#define NSA$M_MNT_NODISKQ                  8
#define NSA$M_MNT_NOHDR3                   16
#define NSA$M_MNT_NOLABEL                  32
#define NSA$M_MNT_NOWRITE                  64
#define NSA$M_MNT_OVR_ACCESS               128
#define NSA$M_MNT_OVR_EXP                  256
#define NSA$M_MNT_OVR_IDENT                512
#define NSA$M_MNT_OVR_SETID                1024
#define NSA$M_MNT_READCHECK                2048
#define NSA$M_MNT_SHARE                    4096
#define NSA$M_MNT_MESSAGE                  8192
#define NSA$M_MNT_SYSTEM                   16384
#define NSA$M_MNT_WRITECHECK               32768
#define NSA$M_MNT_WRITETHRU                65536
#define NSA$M_MNT_NOCACHE                  131072
#define NSA$M_MNT_OVR_LOCK                 262144
#define NSA$M_MNT_NOMNTVER                 524288
#define NSA$M_MNT_NOUNLOAD                 1048576
#define NSA$M_MNT_TAPE_DATA_WRITE          2097152
#define NSA$M_MNT_NOCOPY                   4194304
#define NSA$M_MNT_NOAUTO                   8388608
#define NSA$M_MNT_INIT_ALL                 16777216
#define NSA$M_MNT_INIT_CONT                33554432
#define NSA$M_MNT_OVR_VOLO                 67108864
#define NSA$M_MNT_INTERCHG                 134217728
#define NSA$M_MNT_CLUSTER                  268435456
#define NSA$M_MNT_NOREBUILD                536870912
#define NSA$M_MNT_OVR_SHAMEM               1073741824
#define NSA$M_MNT_MULTI_VOL                -2147483648
#define NSA$V_MNT_FOREIGN                  0
#define NSA$V_MNT_GROUP                    1
#define NSA$V_MNT_NOASSIST                 2
#define NSA$V_MNT_NODISKQ                  3
#define NSA$V_MNT_NOHDR3                   4
#define NSA$V_MNT_NOLABEL                  5
#define NSA$V_MNT_NOWRITE                  6
#define NSA$V_MNT_OVR_ACCESS               7
#define NSA$V_MNT_OVR_EXP                  8
#define NSA$V_MNT_OVR_IDENT                9
#define NSA$V_MNT_OVR_SETID                10
#define NSA$V_MNT_READCHECK                11
#define NSA$V_MNT_SHARE                    12
#define NSA$V_MNT_MESSAGE                  13
#define NSA$V_MNT_SYSTEM                   14
#define NSA$V_MNT_WRITECHECK               15
#define NSA$V_MNT_WRITETHRU                16
#define NSA$V_MNT_NOCACHE                  17
#define NSA$V_MNT_OVR_LOCK                 18
#define NSA$V_MNT_NOMNTVER                 19
#define NSA$V_MNT_NOUNLOAD                 20
#define NSA$V_MNT_TAPE_DATA_WRITE          21
#define NSA$V_MNT_NOCOPY                   22
#define NSA$V_MNT_NOAUTO                   23
#define NSA$V_MNT_INIT_ALL                 24
#define NSA$V_MNT_INIT_CONT                25
#define NSA$V_MNT_OVR_VOLO                 26
#define NSA$V_MNT_INTERCHG                 27
#define NSA$V_MNT_CLUSTER                  28
#define NSA$V_MNT_NOREBUILD                29
#define NSA$V_MNT_OVR_SHAMEM               30
#define NSA$V_MNT_MULTI_VOL                31
#define NSA$V_MNT_DISKQ                    32
#define NSA$V_MNT_COMPACTION               33
#define NSA$V_MNT_INCLUDE                  34
#define NSA$V_MNT_PASS2                    35
#define NSA$V_MNT_OVR_NOFE                 36
#define NSA$V_MNT_SCRATCH                  37
#define NSA$V_MNT_CDROM                    38
#define NSA$V_MNT_XAR                      39
#define NSA$V_MNT_DSI                      40
#define NSA$V_MNT_SUBSYSTEM                41
#define NSA$V_MNT_NOCOMPACTION             42
#define NSA$V_MNT_OVR_SECURITY             43
#define NSA$V_MNT_OVR_LIMITED_SEARCH       44
#define NSA$V_MNT_POOL                     45
#define NSA$M_DMT_NOUNLOAD                 1
#define NSA$M_DMT_UNIT                     2
#define NSA$M_DMT_ABORT                    4
#define NSA$M_DMT_CLUSTER                  8
#define NSA$V_DMT_NOUNLOAD                 0
#define NSA$V_DMT_UNIT                     1
#define NSA$V_DMT_ABORT                    2
#define NSA$V_DMT_CLUSTER                  3
#define NSA$C_OBJ_CREATE                   1
#define NSA$C_OBJ_DELETE                   1
#define NSA$C_OBJ_ACCESS                   1
#define NSA$C_OBJ_DEACCESS                 1
#define NSA$_ACCESS_DESIRED                1
#define NSA$_ACCOUNT                       2
#define NSA$_ALARM_NAME                    3
#define NSA$_APPL_DATA                     4
#define NSA$_AUDIT_FLAGS                   5
#define NSA$_AUDIT_NAME                    6
#define NSA$_SYSTEM_NAME                   7
#define NSA$_SYSTEM_ID                     8
#define NSA$_DEVICE_NAME                   9
#define NSA$_DISMOUNT_FLAGS                10
#define NSA$_HOLDER_NAME                   11
#define NSA$_HOLDER_OWNER                  12
#define NSA$_ID_ATTRIBUTES                 13
#define NSA$_ID_NAME                       14
#define NSA$_ID_NEW_NAME                   15
#define NSA$_ID_VALUE                      16
#define NSA$_ID_NEW_VALUE                  17
#define NSA$_IDENTIFIERS_USED              18
#define NSA$_IMAGE_NAME                    19
#define NSA$_INSTALL_FILE                  20
#define NSA$_INSTALL_FLAGS                 21
#define NSA$_INSTALL_PRIVS                 22
#define NSA$_LOGICAL_NAME                  23
#define NSA$_MOUNT_FLAGS                   24
#define NSA$_NEW_DATA                      25
#define NSA$_FILE_ID                       26
#define NSA$_OBJECT_MIN_CLASS              27
#define NSA$_OBJECT_MAX_CLASS              28
#define NSA$_OBJECT_NAME                   29
#define NSA$_OBJECT_NAME_2                 30
#define NSA$_OBJECT_OWNER                  31
#define NSA$_OBJECT_PROTECTION             32
#define NSA$_OBJECT_TYPE                   33
#define NSA$_ORIGINAL_DATA                 34
#define NSA$_PARENT_ID                     35
#define NSA$_PARENT_NAME                   36
#define NSA$_PARENT_OWNER                  37
#define NSA$_PARENT_USERNAME               38
#define NSA$_PASSWORD                      39
#define NSA$_PRIVS_USED                    40
#define NSA$_PROCESS_ID                    41
#define NSA$_PROCESS_NAME                  42
#define NSA$_REMOTE_NODE_ID                43
#define NSA$_REMOTE_NODENAME               44
#define NSA$_REMOTE_USERNAME               45
#define NSA$_SUBJECT_CLASS                 46
#define NSA$_SUBJECT_OWNER                 47
#define NSA$_FINAL_STATUS                  48
#define NSA$_TERMINAL                      49
#define NSA$_TIME_STAMP                    50
#define NSA$_UAF_ADD                       51
#define NSA$_UAF_DELETE                    52
#define NSA$_UAF_MODIFY                    53
#define NSA$_UAF_COPY                      54
#define NSA$_UAF_FIELDS                    55
#define NSA$_USERNAME                      56
#define NSA$_UAF_SOURCE                    57
#define NSA$_UAF_RENAME                    58
#define NSA$_VOLUME_NAME                   59
#define NSA$_VOLUME_SET_NAME               60
#define NSA$_SERVER_ACCOUNT                61
#define NSA$_SERVER_SYSTEM_ID              62
#define NSA$_SERVER_SYSTEM_NAME            63
#define NSA$_SERVER_FINAL_STATUS           64
#define NSA$_SERVER_IMAGE_NAME             65
#define NSA$_SERVER_PARENT_ID              66
#define NSA$_SERVER_PARENT_OWNER           67
#define NSA$_SERVER_PARENT_NAME            68
#define NSA$_SERVER_PROCESS_ID             69
#define NSA$_SERVER_PROCESS_NAME           70
#define NSA$_SERVER_SUBJECT_CLASS          71
#define NSA$_SERVER_SUBJECT_OWNER          72
#define NSA$_SERVER_TERMINAL               73
#define NSA$_SERVER_TIME_STAMP             74
#define NSA$_SERVER_USERNAME               75
#define NSA$_AUDIT_DISABLE                 76
#define NSA$_AUDIT_ENABLE                  77
#define NSA$_ALARM_DISABLE                 78
#define NSA$_ALARM_ENABLE                  79
#define NSA$_NOP                           80
#define NSA$_REPLY_MAILBOX                 81
#define NSA$_DEFAULT_USERNAME              82
#define NSA$_LOCAL_USERNAME                83
#define NSA$_FIELD_NAME                    84
#define NSA$_LISTENER_DEVICE               85
#define NSA$_FIELD_TITLE_STR               86
#define NSA$_FIELD_DATA_STR                87
#define NSA$_MESSAGE_TYPE_STR              88
#define NSA$_EVENT_TYPE                    89
#define NSA$_EVENT_SUBTYPE                 90
#define NSA$_EVENT_FACILITY                91
#define NSA$_DIRECTORY_ENTRY               92
#define NSA$_DIRECTORY_ID                  93
#define NSA$_CUSTOMER_1                    94
#define NSA$_CUSTOMER_2                    95
#define NSA$_CUSTOMER_3                    96
#define NSA$_CUSTOMER_4                    97
#define NSA$_CUSTOMER_5                    98
#define NSA$_CUSTOMER_6                    99
#define NSA$_CUSTOMER_7                    100
#define NSA$_CUSTOMER_8                    101
#define NSA$_CSS_1                         102
#define NSA$_CSS_2                         103
#define NSA$_CSS_3                         104
#define NSA$_CSS_4                         105
#define NSA$_CSS_5                         106
#define NSA$_CSS_6                         107
#define NSA$_CSS_7                         108
#define NSA$_CSS_8                         109
#define NSA$_LP_1                          110
#define NSA$_LP_2                          111
#define NSA$_LP_3                          112
#define NSA$_LP_4                          113
#define NSA$_LP_5                          114
#define NSA$_LP_6                          115
#define NSA$_LP_7                          116
#define NSA$_LP_8                          117
#define NSA$_ALARM_FAILURE                 118
#define NSA$_AUDIT_FAILURE                 119
#define NSA$_SEVMS_0                       120
#define NSA$_SEVMS_1                       121
#define NSA$_SEVMS_2                       122
#define NSA$_SEVMS_3                       123
#define NSA$_SEVMS_4                       124
#define NSA$_SEVMS_5                       125
#define NSA$_SEVMS_6                       126
#define NSA$_SEVMS_7                       127
#define NSA$_SEVMS_8                       128
#define NSA$_SEVMS_9                       129
#define NSA$_SEVMS_10                      130
#define NSA$_SEVMS_11                      131
#define NSA$_SEVMS_12                      132
#define NSA$_SEVMS_13                      133
#define NSA$_SEVMS_14                      134
#define NSA$_SEVMS_15                      135
#define NSA$_SEVMS_16                      136
#define NSA$_SEVMS_17                      137
#define NSA$_SEVMS_18                      138
#define NSA$_SNAPSHOT_TIME                 139
#define NSA$_TRANSPORT_NAME                140
#define NSA$_DECNET_LINK_ID                141
#define NSA$_DECNET_OBJECT_NAME            142
#define NSA$_DECNET_OBJECT_NUMBER          143
#define NSA$_REMOTE_LINK_ID                144
#define NSA$_COMMAND_LINE                  145
#define NSA$_ASSOCIATION_NAME              146
#define NSA$_REM_ASSOCIATION_NAME          147
#define NSA$_CONNECTION_ID                 148
#define NSA$_MESSAGE                       149
#define NSA$_MSGFILNAM                     150
#define NSA$_OBJECT_POINTER                151
#define NSA$_ID_NEW_ATTRIBUTES             152
#define NSA$_SYSTIM_NEW                    153
#define NSA$_SYSTIM_OLD                    154
#define NSA$_PARAMS_WRITE                  155
#define NSA$_PARAMS_INUSE                  156
#define NSA$_MATCHING_ACE                  157
#define NSA$_SNAPSHOT_SAVE_FILNAM          158
#define NSA$_MAILBOX_UNIT                  159
#define NSA$_NEW_OWNER                     160
#define NSA$_NEW_PRIORITY                  161
#define NSA$_OLD_PRIORITY                  162
#define NSA$_DIAG_FUNC                     163
#define NSA$_RESOURCE_NAME                 164
#define NSA$_LNM_TABLE_NAME                165
#define NSA$_LNM_PARENT_NAME               166
#define NSA$_EFC_NAME                      167
#define NSA$_TARGET_PROCESS_CLASS          168
#define NSA$_TARGET_PROCESS_ID             169
#define NSA$_TARGET_PROCESS_NAME           170
#define NSA$_TARGET_PROCESS_OWNER          171
#define NSA$_TARGET_USERNAME               172
#define NSA$_NEW_PRIVILEGES                173
#define NSA$_OLD_PRIVILEGES                174
#define NSA$_REMOTE_NODE_FULLNAME          175
#define NSA$_UNUSED_2                      176
#define NSA$_UNUSED_3                      177
#define NSA$_UNUSED_4                      178
#define NSA$_UNUSED_5                      179
#define NSA$_UNUSED_6                      180
#define NSA$_UNUSED_7                      181
#define NSA$_UNUSED_8                      182
#define NSA$_UNUSED_9                      183
#define NSA$_UNUSED_10                     184
#define NSA$_PRIVS_MISSING                 185
#define NSA$_TARGET_DEVICE_NAME            186
#define NSA$_SECTION_NAME                  187
#define NSA$_ID_VALUE_ASCII                188
#define NSA$_OBJECT_CLASS                  189
#define NSA$_SUPPRESS                      190
#define NSA$_SNAPSHOT_BOOTFILE             191
#define NSA$_SOURCE_PROCESS_ID             192
#define NSA$_REQUEST_NUMBER                193
#define NSA$_ACCESS_MODE                   194
#define NSA$_SYSTEM_SERVICE_NAME           195
#define NSA$_NEW_AUTH_PRIVILEGES           196
#define NSA$_OLD_AUTH_PRIVILEGES           197
#define NSA$_NEW_DEF_PRIVILEGES            198
#define NSA$_OLD_DEF_PRIVILEGES            199
#define NSA$_NEW_PROCESS_ID                200
#define NSA$_NEW_PROCESS_OWNER             201
#define NSA$_NEW_PROCESS_NAME              202
#define NSA$_NEW_IMAGE_NAME                203
#define NSA$_NEW_USERNAME                  204
#define NSA$_DEACCESS_KEY                  205
#define NSA$_OBJECT_RIGHTS_BLOCK           206
#define NSA$_OBJSRV_COMPLETE               207
#define NSA$_TLV_ORB                       208
#define NSA$_FILE_NAME                     209
#define NSA$_DIRECTORY_NAME                210
#define NSA$_SEQUENCE_KEY                  211
#define NSA$_PRINCIPAL_FULLNAME            212
#define NSA$_TARGET_FULLNAME               213
#define NSA$_SOURCE_FULLNAME               214
#define NSA$_DESIRED_FULLNAME              215
#define NSA$_CLAIMED_USERNAME              216
#define NSA$_CLAIMED_FULLNAME              217
#define NSA$_CLAIMED_NODENAME              218
#define NSA$_TIME_REQ                      219
#define NSA$_TIME_REC                      220
#define NSA$_REQ_FLAGS                     221
#define NSA$_RET_FLAGS                     222
#define NSA$_LIFETIME_REQ                  223
#define NSA$_LIFETIME_REC                  224
#define NSA$_CRED_USAGE                    225
#define NSA$_CONTEXT_HANDLE                226
#define NSA$_QOP_STATE                     227
#define NSA$_CONF_STATE                    228
#define NSA$_DELEG_CRED_HANDLE             229
#define NSA$_MAJOR_STATUS                  230
#define NSA$_DAS_1                         231
#define NSA$_DAS_2                         232
#define NSA$_DAS_3                         233
#define NSA$_DAS_4                         234
#define NSA$_DAS_5                         235
#define NSA$_DAS_6                         236
#define NSA$_DAS_7                         237
#define NSA$_DAS_8                         238
#define NSA$_DAS_9                         239
#define NSA$_DAS_10                        240
#define NSA$_STATE_FILE_NAME               241
#define NSA$_DIRECTORY_FULLNAME            242
#define NSA$_FROM_DIRECTORY_FULLNAME       243
#define NSA$_TO_DIRECTORY_FULLNAME         244
#define NSA$_ISSUER_FULLNAME               245
#define NSA$_SUBJECT_FULLNAME              246
#define NSA$_CERTIF_TYPE                   247
#define NSA$_CSS_SECONDARY_NAME            248
#define NSA$_CSS_OBJECT_FULLNAME           249
#define NSA$_CSS_REQUEST_FROM              250
#define NSA$_CSS_PRIMARY_NAME              251
#define NSA$_CERTIF_SERIAL_NUMBER          252
#define NSA$_WINDOW_END_TIME               253
#define NSA$_LOG_CLOSED                    254
#define NSA$_LOG_OPENED                    255
#define NSA$_IDENTIFIERS_MISSING           256
#define NSA$_SENSITIVE_FIELD_NAME          257
#define NSA$_SENSITIVE_ORIG_DATA           258
#define NSA$_SENSITIVE_NEW_DATA            259
#define NSA$_SENSITIVE_FIELD_TITLE         260
#define NSA$_SENSITIVE_FIELD_DATA          261
#define NSA$_MAX_ITM_CODE                  262
#define NSA$_CHAIN                         65535
#define NSA$_CLIENT_ACCOUNT                2
#define NSA$_CLIENT_SYSTEM_ID              8
#define NSA$_CLIENT_SYSTEM_NAME            7
#define NSA$_CLIENT_FINAL_STATUS           48
#define NSA$_CLIENT_IMAGE_NAME             19
#define NSA$_CLIENT_PARENT_ID              35
#define NSA$_CLIENT_PARENT_OWNER           37
#define NSA$_CLIENT_PARENT_NAME            36
#define NSA$_CLIENT_PROCESS_ID             41
#define NSA$_CLIENT_PROCESS_NAME           42
#define NSA$_CLIENT_SUBJECT_CLASS          46
#define NSA$_CLIENT_SUBJECT_OWNER          47
#define NSA$_CLIENT_TERMINAL               49
#define NSA$_CLIENT_TIME_STAMP             50
#define NSA$_CLIENT_USERNAME               56
#define NSA$M_ACCOUNT_NAME                 1
#define NSA$M_SYSTEM_ID                    2
#define NSA$M_SYSTEM_NAME                  4
#define NSA$M_FINAL_STATUS                 8
#define NSA$M_IMAGE_NAME                   16
#define NSA$M_PARENT_ID                    32
#define NSA$M_PARENT_OWNER                 64
#define NSA$M_PARENT_NAME                  128
#define NSA$M_PROCESS_ID                   256
#define NSA$M_PROCESS_NAME                 512
#define NSA$M_SUBJECT_CLASS                1024
#define NSA$M_SUBJECT_OWNER                2048
#define NSA$M_TERMINAL                     4096
#define NSA$M_TIME_STAMP                   8192
#define NSA$M_USERNAME                     16384
#define NSA$M_PARENT_USERNAME              32768
#define NSA$V_ACCOUNT_NAME                 0
#define NSA$V_SYSTEM_ID                    1
#define NSA$V_SYSTEM_NAME                  2
#define NSA$V_FINAL_STATUS                 3
#define NSA$V_IMAGE_NAME                   4
#define NSA$V_PARENT_ID                    5
#define NSA$V_PARENT_OWNER                 6
#define NSA$V_PARENT_NAME                  7
#define NSA$V_PROCESS_ID                   8
#define NSA$V_PROCESS_NAME                 9
#define NSA$V_SUBJECT_CLASS                10
#define NSA$V_SUBJECT_OWNER                11
#define NSA$V_TERMINAL                     12
#define NSA$V_TIME_STAMP                   13
#define NSA$V_USERNAME                     14
#define NSA$V_PARENT_USERNAME              15
#define NSA$M_FMTINF_CHECK_PREVIOUS        1
#define NSA$M_FMTINF_NTH_NEW_LINE          2
#define NSA$M_FMTINF_NOFORMAT              4
#define NSA$M_FMTINF_SENSITIVE             8
#define NSA$C_FORMAT_STYLE_BRIEF           1
#define NSA$C_FORMAT_STYLE_FULL            2
#define NSA$C_FORMAT_STYLE_PACKET_TYPE     3
#define NSA$V_FMTINF_CHECK_PREVIOUS        0
#define NSA$V_FMTINF_NTH_NEW_LINE          1
#define NSA$V_FMTINF_NOFORMAT              2
#define NSA$V_FMTINF_SENSITIVE             3
#define NSA$M_FMTARG_SENSITIVE             1
#define NSA$M_FMTARG_DISPLAY_TITLE         2
#define NSA$M_FMTARG_CHECK_PREVIOUS        1
#define NSA$M_FMTARG_NTH_NEW_LINE          2
#define NSA$M_FMTARG_NOFORMAT              4
#define NSA$V_FMTARG_SENSITIVE             0
#define NSA$V_FMTARG_DISPLAY_TITLE         1
#define NSA$V_FMTARG_CHECK_PREVIOUS        0
#define NSA$V_FMTARG_NTH_NEW_LINE          1
#define NSA$V_FMTARG_NOFORMAT              2
#define NSA$C_MSG_NETUAF                   9
#define NSA$C_MSG_PRIV_AUDIT               16
#define NSA$_OBJECT_ID                     26
#define NSA$_PRIV_MASK                     22
#define NSA$_PRIVILEGES                    22
#define NSA$_SNAPSHOT_FILNAM               158
#define NSA$_PERFORMANCE_NOP               80
#define NSA$_SUPPLIED_FLAGS                190

#ifdef __cplusplus
}
#endif

#endif /* __NSADEF_H */
