/*
 * prv_names.h - Single X-macro source for vms_priv_names[] (the DCL
 *               privilege display table, src/vmsdcl/dcl_cmd_show.c) and
 *               for the compile-time coverage mask checked against
 *               VMS_PRV_M_ENFORCED in src/libvms/prv_agreement.c (vms-2b8
 *               round 10).
 *
 * WHY THIS FILE EXISTS. Round 9's prv_agreement.c added a _Static_assert
 * that VMS_PRV_M_ENFORCED (src/kernel/vms_ioctl.h) names no bit outside a
 * HAND-TYPED list `(PRV$M_CMKRNL | PRV$M_CMEXEC | PRV$M_SETPRV |
 * PRV$M_WORLD)`. That list was maintained by a human reading
 * vms_priv_names[] and copying which of its rows cover VMS_PRV_M_ENFORCED
 * -- it asserted the whitelist agreed with ITSELF, not with the array. An
 * adversary proved the gap by deleting the WORLD row from vms_priv_names[]
 * outright: the build still succeeded, because nothing in prv_agreement.c
 * ever looked at the array's actual contents, only at a second, independent
 * copy of "which four" a person had typed by hand.
 *
 * THE FIX moves that array's actual content into ONE preprocessor list
 * (VMS_PRIV_NAME_LIST below) and derives BOTH consumers from it:
 *   - dcl_cmd_show.c's vms_priv_names[] is generated by expanding this
 *     list through VMS_PRIV_ROW_ENTRY, one struct initializer per line.
 *   - prv_agreement.c's coverage mask (VMS_PRIV_NAMES_TABLE_MASK) is the
 *     OR of every mask in this SAME list, expanded through
 *     VMS_PRIV_MASK_TERM.
 * Deleting a line from VMS_PRIV_NAME_LIST removes that privilege from the
 * displayed table AND from the coverage mask in the same edit, because
 * both are generated from that one line. Measured: deleting the WORLD
 * line fails the build at prv_agreement.c's assert, and so does OR-ing an
 * uncovered bit into VMS_PRV_M_ENFORCED -- the desync is a compile error
 * in both directions. See prv_agreement.c for the assert and its two
 * negative controls.
 *
 * WHAT THIS DOES NOT COVER, measured rather than assumed: the guarantee
 * holds while vms_priv_names[] is GENERATED from this list. Replacing the
 * VMS_PRIV_NAME_LIST(VMS_PRIV_ROW_ENTRY) expansion in dcl_cmd_show.c with
 * hand-typed rows that omit one privilege builds clean and passes ctest --
 * the coverage mask still names the bit, the array no longer carries the
 * row, and nothing stops it. Keep the array generated.
 *
 * CONTENT is unchanged from the array round 9 shipped: same 37 entries,
 * same order, same names, same masks, same description strings. DETACH
 * and SETPRI (and every other prvdef.h bit vms_priv_names[] never carried)
 * are still deliberately absent -- CLAUDE.md Rule 10, unchanged by this
 * refactor.
 */

#ifndef __PRV_NAMES_H
#define __PRV_NAMES_H

#include "prvdef.h"

#ifdef __cplusplus
extern "C" {
#endif

#define VMS_PRIV_NAME_LIST(X) \
    X(ACNT,        PRV$M_ACNT,        "may suppress accounting messages") \
    X(ALLSPOOL,    PRV$M_ALLSPOOL,    "may allocate spooled device") \
    X(ALTPRI,      PRV$M_ALTPRI,      "may set any priority value") \
    X(BUGCHK,      PRV$M_BUGCHK,      "may make bug check log entries") \
    X(BYPASS,      PRV$M_BYPASS,      "may bypass all object access controls") \
    X(CMEXEC,      PRV$M_CMEXEC,      "may change mode to exec") \
    X(CMKRNL,      PRV$M_CMKRNL,      "may change mode to kernel") \
    X(IMPERSONATE, PRV$M_IMPERSONATE, "may impersonate another user") \
    X(DIAGNOSE,    PRV$M_DIAGNOSE,    "may diagnose devices") \
    X(DOWNGRADE,   PRV$M_DOWNGRADE,   "may downgrade object secrecy") \
    X(EXQUOTA,     PRV$M_EXQUOTA,     "may exceed disk quota") \
    X(GROUP,       PRV$M_GROUP,       "may affect other processes in same group") \
    X(GRPNAM,      PRV$M_GRPNAM,      "may insert in group logical name table") \
    X(GRPPRV,      PRV$M_GRPPRV,      "may access group objects via system protection") \
    X(LOG_IO,      PRV$M_LOG_IO,      "may do logical i/o") \
    X(MOUNT,       PRV$M_MOUNT,       "may execute mount acp function") \
    X(NETMBX,      PRV$M_NETMBX,      "may create network device") \
    X(OPER,        PRV$M_OPER,        "may perform operator functions") \
    X(PFNMAP,      PRV$M_PFNMAP,      "may map to specific physical pages") \
    X(PHY_IO,      PRV$M_PHY_IO,      "may do physical i/o") \
    X(PRMCEB,      PRV$M_PRMCEB,      "may create permanent common event clusters") \
    X(PRMGBL,      PRV$M_PRMGBL,      "may create permanent global sections") \
    X(PRMMBX,      PRV$M_PRMMBX,      "may create permanent mailbox") \
    X(PSWAPM,      PRV$M_PSWAPM,      "may change process swap mode") \
    X(READALL,     PRV$M_READALL,     "may read anything as the owner") \
    X(SECURITY,    PRV$M_SECURITY,    "may perform security administration functions") \
    X(SETPRV,      PRV$M_SETPRV,      "may set any privilege bit") \
    X(SHARE,       PRV$M_SHARE,       "may assign channels to non-shared devices") \
    X(SHMEM,       PRV$M_SHMEM,       "may create/delete objects in shared memory") \
    X(SYSGBL,      PRV$M_SYSGBL,      "may create system wide global sections") \
    X(SYSLCK,      PRV$M_SYSLCK,      "may lock system wide resources") \
    X(SYSNAM,      PRV$M_SYSNAM,      "may insert in system logical name table") \
    X(SYSPRV,      PRV$M_SYSPRV,      "may access objects via system protection") \
    X(TMPMBX,      PRV$M_TMPMBX,      "may create temporary mailbox") \
    X(UPGRADE,     PRV$M_UPGRADE,     "may upgrade object integrity") \
    X(VOLPRO,      PRV$M_VOLPRO,      "may override volume protection") \
    X(WORLD,       PRV$M_WORLD,       "may affect other processes in the world")

/* Expands to one `{ "NAME", mask, "desc" },` per VMS_PRIV_NAME_LIST entry.
 * Used by dcl_cmd_show.c to build vms_priv_names[]. */
#define VMS_PRIV_ROW_ENTRY(name, mask, desc) { #name, mask, desc },

/* Expands to `| (mask)` per entry; OR'd against 0 below to produce a single
 * compile-time constant covering every bit ANY row in the table sets. Used
 * by prv_agreement.c to check VMS_PRV_M_ENFORCED against the table's real
 * content instead of a hand-copied subset. */
#define VMS_PRIV_MASK_TERM(name, mask, desc) | (mask)
#define VMS_PRIV_NAMES_TABLE_MASK (0 VMS_PRIV_NAME_LIST(VMS_PRIV_MASK_TERM))

#ifdef __cplusplus
}
#endif

#endif /* __PRV_NAMES_H */
