#!/usr/bin/env python3
"""gen_msgcat.py - the OVMX message catalog from the observed OpenVMS one (rd vms-546).

docs/oracle/messages/alpha84-msgcat*.txt hold what $GETMSG returned on a real
OpenVMS Alpha V8.4 node for every message number of the facilities captured
(tools/oracle/messages/SP_MSGCAT*.MAR, run by capture). Each line:

    MC <condition value> <$GETMSG outadr longword> %FAC-W-IDENT, text

This writes src/libvms/include/ovmx_msgcat.inc, the table $GETMSG/$PUTMSG
(src/libvms/syssvc/sys_msg.c) answer from: the SYSTEM facility's messages (its
low message numbers are the SHARED messages every facility uses), plus each
other facility's facility-specific ones (message number bit 12 set), plus the
facility names. The .inc is GENERATED -- never edit it; --check (a ctest) fails
when it is not what this script would write.
"""
import glob
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SRC = sorted(glob.glob(os.path.join(ROOT, "docs/oracle/messages/alpha84-msgcat*.txt")))
OUT = os.path.join(ROOT, "src/libvms/include/ovmx_msgcat.inc")
LINE = re.compile(r"^MC ([0-9A-F]{8}) ([0-9A-F]{8}) %([A-Z0-9$_]+)-W-([A-Z0-9$_]+)(?:, (.*))?$")


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build():
    msgs, facs = {}, {}
    for path in SRC:
        for raw in open(path, encoding="latin-1"):
            raw = raw.rstrip("\n")
            m = LINE.match(raw)
            if not m or m.group(4) == "NOMSG":
                continue
            code, outadr = int(m.group(1), 16), int(m.group(2), 16)
            fac, num = (code >> 16) & 0xFFF, (code >> 3) & 0x1FFF
            facs.setdefault(fac, m.group(3))
            if fac != 0 and not (num & 0x1000):
                # a SHARED message: SYSTEM's own. Keep it as SYSTEM's when the
                # SYSTEM capture lacks it -- message 0 (NORMAL), whose SYSTEM
                # condition value 0 is the one value $GETMSG never names.
                shared = num << 3
                if shared not in msgs and shared != 0 or (shared == 0 and 0 not in msgs):
                    msgs[shared] = ((outadr >> 8) & 0xFF, m.group(4), m.group(5) or "")
                continue
            faocnt = (outadr >> 8) & 0xFF
            msgs[code] = (faocnt, m.group(4), m.group(5) or "")
    out = ["/* GENERATED by tools/oracle/messages/gen_msgcat.py from",
           " * docs/oracle/messages/alpha84-msgcat*.txt -- the message catalog observed",
           " * on OpenVMS Alpha V8.4 ($GETMSG of every message number). DO NOT EDIT. */",
           "static const struct ovmx_msgfac ovmx_msgfacs[] = {"]
    for fac in sorted(facs):
        out.append("    { %d, %s }," % (fac, cstr(facs[fac])))
    out.append("};")
    out.append("static const struct ovmx_msgdef ovmx_msgcat[] = {")
    for code in sorted(msgs):
        n, ident, text = msgs[code]
        out.append("    { 0x%08Xu, %d, %s, %s }," % (code, n, cstr(ident), cstr(text)))
    out.append("};")
    return "\n".join(out) + "\n"


def main(argv):
    text = build()
    if "--check" in argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("FAIL: %s is stale -- run tools/oracle/messages/gen_msgcat.py" % OUT)
            return 1
        print("OK: %s is current (%d lines)" % (OUT, text.count("\n")))
        return 0
    open(OUT, "w").write(text)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
