@case Q.IODELTA2
@title probe: JPI$_BUFIO / JPI$_DIRIO per operation -- TYPE of 3 and 7 records, OPEN, READ, CLOSE, DIRECTORY, WRITE
S0 send "SET DEFAULT SYS$LOGIN\r" expect="\$ $" quiet
T1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
T2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
T3 send "TYPE KSE2.TXT\r" expect="\$ $"
T4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
U1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
U2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
U3 send "TYPE KSPG.COM\r" expect="\$ $"
U4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
O1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
O2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
O3 send "OPEN F KSPG.COM\r" expect="\$ $"
O4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
R1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
R2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
R3 send "READ F X\r" expect="\$ $"
R4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
C1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
C2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
C3 send "CLOSE F\r" expect="\$ $"
C4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
D1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
D2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
D3 send "DIRECTORY KSPG.COM\r" expect="\$ $"
D4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
W1 send "$ B=F$GETJPI(\"\",\"BUFIO\")\r" expect="\$ $"
W2 send "$ D=F$GETJPI(\"\",\"DIRIO\")\r" expect="\$ $"
W3 send "WRITE SYS$OUTPUT \"X\"\r" expect="\$ $"
W4 send "$ WRITE SYS$OUTPUT F$GETJPI(\"\",\"BUFIO\")-B,\" \",F$GETJPI(\"\",\"DIRIO\")-D\r" expect="\$ $"
