/*
 * test_dnet_routing_fuzz.c - systematic ASan/UBSan fuzz + bound proof of the
 * DECnet Phase IV routing RECEIVE path (rd vms-aac0).
 *
 * WHY THIS EXISTS (⭐⭐ never crash a peer -- and never let a peer crash us):
 * before an OVMX node exchanges DECnet adjacency with a LIVE real OpenVMS VAX
 * peer (the rd vms-aac0 lab campaign), we must PROVE the routing receive path
 * cannot be crashed / over-read / driven into UB by ANY frame a peer could put
 * on the wire. The router-hello codec in particular is SPEC-DERIVED (no
 * oracle wire specimen exists -- see dnet_router_hello.h), so it has never met
 * real wire and MUST be sanitizer-fuzz-hardened before it ever does.
 *
 * WHAT IT COVERS (the receive path a peer can reach):
 *   1. dnet_router_hello_decode  -- >=200k fuzzed + structured-malformed inputs
 *   2. dnet_hello_decode         -- >=200k fuzzed + structured-malformed inputs
 *   3. dnet_adj_rx_hello (FSM)   -- >=200k adversarial state-machine sequences
 *      fed VALID-but-hostile HELLOs (reordered / repeated / peers naming or not
 *      naming us / table-overflow / backward + huge `now` ticks)
 *   4. POSITIVE liveness: a well-formed two-way endnode-HELLO sequence drives a
 *      neighbour to DNET_ADJ_UP (the exact live-adjacency path vms-aac0 uses --
 *      the adjacency FSM in this module consumes ENDNODE hellos; a router hello
 *      is decoded by its own codec, which is round-tripped encode->decode here),
 *      and a well-formed router-hello round-trips encode->decode.
 *
 * ANTI-LARP / TEETH: this file is BUILT WITH -fsanitize=address,undefined by
 * its CMake target, so an over-read / OOB / UB in any decoder or in the FSM is
 * a HARD test failure, not a silent pass. The exit code is NOT swallowed. On a
 * logic-invariant violation the offending input is dumped as hex with its
 * replay coordinates; on a sanitizer fault ASan/UBSan prints its own report and
 * aborts (nonzero exit). Inputs are generated by a PURE, per-iteration-seeded
 * splitmix64 stream so ANY iteration is replayable from the printed base seed.
 *
 * Teeth were confirmed out-of-tree: with the `len < LENPREFIX + msglen` bound
 * removed from a scratch copy of dnet_router_hello_decode, this exact fuzz trips
 * an ASan heap-buffer-overflow within the first few thousand iterations (the
 * memcpy of the E-list reads past the short buffer). The check is present in
 * the shipped codec, so the fuzz stays silent -- proving the harness has teeth
 * against a real OOB without weakening the codec.
 *
 * Clean-room (CLAUDE.md Rule 8): no VSI/HPE/DEC source consulted; this is a
 * test harness over OVMX's own codecs.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "dnet_hello.h"
#include "dnet_router_hello.h"
#include "dnet_adjacency.h"

/* rd vms-abf: detect whether AddressSanitizer is actually compiled in. The
 * -fsanitize flags are applied only if the CheckCSourceCompiles probe in
 * CMakeLists succeeds; a CI image lacking the ASan runtime would silently
 * disable them, leaving this crash-vector proof TOOTHLESS while still passing.
 * When OVMX_FUZZ_REQUIRE_SANITIZERS is set (the gated CI leg sets it), the test
 * HARD-FAILS unless ASan is active -- a toothless run reds instead of silently
 * re-opening the receive-path crash vector. */
#if defined(__SANITIZE_ADDRESS__)
#  define OVMX_FUZZ_ASAN_ACTIVE 1
#elif defined(__has_feature)
#  if __has_feature(address_sanitizer)
#    define OVMX_FUZZ_ASAN_ACTIVE 1
#  else
#    define OVMX_FUZZ_ASAN_ACTIVE 0
#  endif
#else
#  define OVMX_FUZZ_ASAN_ACTIVE 0
#endif

/* Iteration counts (each >= the 200k the item mandates; sized so the whole
 * ctest runs well under 60s even under ASan+UBSan -- see the measured runtime
 * reported in the item). */
#define FUZZ_ITERS_ROUTER  250000
#define FUZZ_ITERS_HELLO   250000
#define FUZZ_ITERS_FSM     250000

/* Fixed base seed => fully reproducible. Any single iteration `i` of a phase is
 * replayable by seeding the generator with (BASE_SEED ^ phase_salt) + i. */
#define BASE_SEED  0xA1B2C3D4E5F60718ULL

static int g_fail = 0;
#define CHECK(c, msg) do { \
    if (c) { /* pass, quiet */ } \
    else { g_fail++; printf("  FAIL: %s\n", msg); } \
} while (0)

/* ---- pure, per-iteration-seeded PRNG (splitmix64) ------------------------ */
/* Deterministic and libc-rand-independent so a run is byte-for-byte replayable
 * from the printed seed. Each iteration gets its OWN independent stream so a
 * failing iteration index is a complete, standalone reproduction. */
static inline uint64_t sm64(uint64_t *s)
{
    uint64_t z = (*s += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

/* Largest buffer we ever generate: comfortably past a maximal valid frame
 * (router: 2 + 18 + 128 = 148; endnode: 2 + 32 + 128 = 162) so "huge"/oversized
 * cases and every truncation offset are covered. */
#define FUZZ_MAXBUF 512

static void dump_hex(const char *tag, uint64_t phase_salt, unsigned i,
                     const uint8_t *b, size_t n)
{
    printf("  REPLAY %s: seed=0x%016llx phase_salt=0x%016llx iter=%u len=%zu bytes=",
           tag, (unsigned long long)BASE_SEED,
           (unsigned long long)phase_salt, i, n);
    for (size_t k = 0; k < n; k++)
        printf("%02x", b[k]);
    printf("\n");
}

/*
 * Copy `n` fuzzed bytes into a heap allocation of EXACTLY `n` bytes. Passing
 * this exact-size buffer to a decoder is what gives ASan real teeth: with a
 * fixed-size stack buffer, ASan sees the whole array as valid and a read past
 * the logical length `n` (but within the array) is INVISIBLE; with a malloc(n)
 * buffer, ANY read at offset >= n is a hard heap-buffer-overflow. Caller frees.
 * (n == 0 -> a 1-byte allocation the decoder never reads, since len<prefix
 * short-circuits before any dereference.)
 */
static uint8_t *heap_exact(const uint8_t *src, size_t n)
{
    uint8_t *h = (uint8_t *)malloc(n ? n : 1);
    if (h && n)
        memcpy(h, src, n);
    return h;
}

/*
 * Fill `buf` with a fuzzed input of random length in [0, FUZZ_MAXBUF]. Four
 * generation modes, chosen by the stream, so we cover BOTH unstructured noise
 * and structured-but-malformed frames that reach deep into the decoder:
 *   0 = pure random bytes, random length (incl. 0, 1, tiny, huge)
 *   1 = tiny (0..7 bytes): exercises every early-length guard
 *   2 = structured: a plausible LE length prefix aimed at boundary msglen
 *       values (fixed-1/fixed/fixed+1, cap-1/cap/cap+1, giant, 0xffff) with a
 *       body length chosen to be truncated / exact / oversized independently of
 *       that prefix -- i.e. "valid length prefix but inconsistent DATA LENGTH",
 *       "elistlen at/above the MAX cap boundary", truncation at a field offset.
 *   3 = structured with a random offset field zeroed/poked, to walk truncations
 *       and single-field corruptions of an otherwise plausible frame.
 * `fixed` is the codec's FIXED_MSG (18 router / 32 endnode); `maxvar` its
 * variable-field cap (MAX_ELIST / MAX_DATA). Layout-agnostic otherwise.
 */
static size_t gen_input(uint64_t *st, uint8_t *buf, unsigned fixed, unsigned maxvar)
{
    unsigned mode = (unsigned)(sm64(st) & 3u);
    size_t n;

    if (mode == 1) {
        n = (size_t)(sm64(st) % 8u);
    } else {
        n = (size_t)(sm64(st) % (FUZZ_MAXBUF + 1));
    }
    for (size_t k = 0; k < n; k++)
        buf[k] = (uint8_t)sm64(st);

    if ((mode == 2 || mode == 3) && n >= 2) {
        /* Pick a boundary-ish msglen for the LE prefix. */
        static const int pick_kind = 8;
        unsigned kind = (unsigned)(sm64(st) % pick_kind);
        uint32_t msglen;
        switch (kind) {
        case 0: msglen = fixed - 1u; break;
        case 1: msglen = fixed; break;
        case 2: msglen = fixed + 1u; break;
        case 3: msglen = fixed + maxvar - 1u; break;
        case 4: msglen = fixed + maxvar; break;      /* var-field exactly at cap */
        case 5: msglen = fixed + maxvar + 1u; break; /* one past the cap */
        case 6: msglen = 0xffffu; break;             /* oversized */
        default: msglen = (uint32_t)(sm64(st) % 400u); break;
        }
        buf[0] = (uint8_t)(msglen & 0xff);
        buf[1] = (uint8_t)((msglen >> 8) & 0xff);

        if (mode == 3 && n > 2) {
            /* poke/zero a single field offset -> single-field corruption + a
             * truncation lever independent of the prefix. */
            size_t off = 2 + (size_t)(sm64(st) % (n - 2));
            buf[off] = (uint8_t)((sm64(st) & 1u) ? 0x00 : (uint8_t)sm64(st));
        }
    }
    return n;
}

/* ---- 1. fuzz the router-hello decoder ------------------------------------ */
static void fuzz_router_hello(void)
{
    const uint64_t salt = 0x1111111111111111ULL;
    uint8_t buf[FUZZ_MAXBUF];
    unsigned ok = 0, err = 0, bad = 0;

    for (unsigned i = 0; i < FUZZ_ITERS_ROUTER; i++) {
        uint64_t st = BASE_SEED ^ salt;
        st += i;                                   /* independent per-iter stream */
        size_t n = gen_input(&st, buf,
                             DNET_ROUTER_HELLO_FIXED_MSG,
                             DNET_ROUTER_HELLO_MAX_ELIST);

        struct dnet_router_hello m;
        size_t consumed = 0xdeadbeef;
        uint8_t *hb = heap_exact(buf, n);      /* exact-size => ASan has teeth */
        int rc = dnet_router_hello_decode(hb, n, &m, &consumed);
        free(hb);

        if (rc == DNET_ROUTER_HELLO_OK) {
            ok++;
            /* Output invariants on success. ASan/UBSan already proved no field
             * was read outside [buf, buf+n); these assert the CONTRACT. */
            int inv = (consumed <= n) &&
                      (m.elist_len <= DNET_ROUTER_HELLO_MAX_ELIST) &&
                      (consumed == (size_t)DNET_ROUTER_HELLO_LENPREFIX
                                   + DNET_ROUTER_HELLO_FIXED_MSG + m.elist_len);
            if (!inv) { bad++; dump_hex("router", salt, i, buf, n); }

            /* Decode->encode->decode stability: a well-formed message survives
             * a full round-trip with identical fixed fields + E-list. */
            uint8_t re[FUZZ_MAXBUF]; size_t rl = 0;
            if (dnet_router_hello_encode(&m, re, sizeof re, &rl) == DNET_ROUTER_HELLO_OK) {
                struct dnet_router_hello m2; size_t c2 = 0;
                if (dnet_router_hello_decode(re, rl, &m2, &c2) == DNET_ROUTER_HELLO_OK) {
                    int same = m2.elist_len == m.elist_len &&
                               memcmp(m2.id, m.id, DNET_ADDR_LEN) == 0 &&
                               m2.rflags == m.rflags && m2.blksize == m.blksize &&
                               m2.priority == m.priority && m2.timer == m.timer &&
                               memcmp(m2.elist, m.elist, m.elist_len) == 0;
                    if (!same) { bad++; dump_hex("router-rt", salt, i, buf, n); }
                } else { bad++; dump_hex("router-rt-dec", salt, i, buf, n); }
            }
        } else {
            err++;
            /* Every non-OK must be a DEFINED error code, never a stray value. */
            int defined = rc == DNET_ROUTER_HELLO_ETRUNC ||
                          rc == DNET_ROUTER_HELLO_EBADLEN ||
                          rc == DNET_ROUTER_HELLO_EINVAL;
            if (!defined) { bad++; dump_hex("router-rc", salt, i, buf, n); }
        }
    }
    printf("  router-hello fuzz: %u iters (%u OK / %u rejected), %u invariant breaks\n",
           FUZZ_ITERS_ROUTER, ok, err, bad);
    CHECK(bad == 0, "router-hello decoder: fuzz clean (no crash/OOB/UB, invariants hold)");
    CHECK(ok > 0, "router-hello fuzz reached the success path (invariants actually exercised)");
}

/* ---- 2. fuzz the endnode-hello decoder ----------------------------------- */
static void fuzz_endnode_hello(void)
{
    const uint64_t salt = 0x2222222222222222ULL;
    uint8_t buf[FUZZ_MAXBUF];
    unsigned ok = 0, err = 0, bad = 0;

    for (unsigned i = 0; i < FUZZ_ITERS_HELLO; i++) {
        uint64_t st = BASE_SEED ^ salt;
        st += i;
        size_t n = gen_input(&st, buf, DNET_HELLO_FIXED_MSG, DNET_HELLO_MAX_DATA);

        struct dnet_endnode_hello m;
        size_t consumed = 0xdeadbeef;
        uint8_t *hb = heap_exact(buf, n);      /* exact-size => ASan has teeth */
        int rc = dnet_hello_decode(hb, n, &m, &consumed);
        free(hb);

        if (rc == DNET_HELLO_OK) {
            ok++;
            int inv = (consumed <= n) &&
                      (m.datalen <= DNET_HELLO_MAX_DATA) &&
                      (consumed == (size_t)DNET_HELLO_LENPREFIX
                                   + DNET_HELLO_FIXED_MSG + m.datalen);
            if (!inv) { bad++; dump_hex("endnode", salt, i, buf, n); }

            uint8_t re[FUZZ_MAXBUF]; size_t rl = 0;
            if (dnet_hello_encode(&m, re, sizeof re, &rl) == DNET_HELLO_OK) {
                struct dnet_endnode_hello m2; size_t c2 = 0;
                if (dnet_hello_decode(re, rl, &m2, &c2) == DNET_HELLO_OK) {
                    int same = m2.datalen == m.datalen &&
                               memcmp(m2.id, m.id, DNET_ADDR_LEN) == 0 &&
                               memcmp(m2.neighbor, m.neighbor, DNET_ADDR_LEN) == 0 &&
                               m2.timer == m.timer && m2.rflags == m.rflags &&
                               memcmp(m2.data, m.data, m.datalen) == 0;
                    if (!same) { bad++; dump_hex("endnode-rt", salt, i, buf, n); }
                } else { bad++; dump_hex("endnode-rt-dec", salt, i, buf, n); }
            }
        } else {
            err++;
            int defined = rc == DNET_HELLO_ETRUNC ||
                          rc == DNET_HELLO_EBADLEN ||
                          rc == DNET_HELLO_EINVAL;
            if (!defined) { bad++; dump_hex("endnode-rc", salt, i, buf, n); }
        }
    }
    printf("  endnode-hello fuzz: %u iters (%u OK / %u rejected), %u invariant breaks\n",
           FUZZ_ITERS_HELLO, ok, err, bad);
    CHECK(bad == 0, "endnode-hello decoder: fuzz clean (no crash/OOB/UB, invariants hold)");
    CHECK(ok > 0, "endnode-hello fuzz reached the success path (invariants actually exercised)");
}

static inline int valid_state(enum dnet_adj_state s)
{
    return s == DNET_ADJ_DOWN || s == DNET_ADJ_INITIALIZING || s == DNET_ADJ_UP;
}

/*
 * Build a VALID, in-range endnode HELLO from the PRNG. We fuzz the FSM with
 * *decodable* hellos (a peer can only feed us frames that survive the decoder
 * anyway), but with adversarial CONTENT: random ids drawn from a small pool so
 * neighbours repeat / reorder / overflow the 32-slot table, timers incl. 0, and
 * a neighbour field that sometimes names US (two-way) and sometimes does not.
 */
static struct dnet_endnode_hello mk_fuzz_hello(uint64_t *st, const uint8_t my_id[6])
{
    struct dnet_endnode_hello h;
    memset(&h, 0, sizeof h);
    h.rflags  = DNET_RFLAG_ENDNODE_HELLO;
    h.version = (uint8_t)sm64(st);
    h.iinfo   = (uint8_t)sm64(st);
    h.blksize = (uint16_t)sm64(st);
    h.timer   = (uint16_t)((sm64(st) & 7u) ? (uint16_t)sm64(st) : 0u); /* incl 0 */
    /* random TEST DATA length in [0, MAX] so the variable-field decode path is
     * exercised too (incl. the exact-cap boundary). */
    h.datalen = (uint8_t)(sm64(st) % (DNET_HELLO_MAX_DATA + 1u));
    for (unsigned d = 0; d < h.datalen; d++)
        h.data[d] = (uint8_t)sm64(st);
    /* id from a pool of ~40 distinct values (> the 32-slot table => overflow). */
    h.id[0] = 0xaa; h.id[1] = 0x00; h.id[2] = 0x04; h.id[3] = 0x00;
    h.id[4] = (uint8_t)(sm64(st) % 40u);
    h.id[5] = 0x04;
    /* neighbour field: ~1/3 of the time name US (drives two-way), else random. */
    if ((sm64(st) % 3u) == 0) {
        memcpy(h.neighbor, my_id, 6);
    } else {
        h.neighbor[0] = 0xaa; h.neighbor[1] = 0x00; h.neighbor[2] = 0x04;
        h.neighbor[3] = 0x00; h.neighbor[4] = (uint8_t)sm64(st); h.neighbor[5] = (uint8_t)sm64(st);
    }
    return h;
}

/* ---- 3. fuzz the adjacency FSM with adversarial sequences ---------------- */
static void fuzz_adjacency_fsm(void)
{
    const uint64_t salt = 0x3333333333333333ULL;
    static const uint8_t my_id[6] = { 0xaa, 0x00, 0x04, 0x00, 0x01, 0x04 };
    unsigned bad = 0, reached_up = 0;

    struct dnet_adjacency sm;
    dnet_adj_init(&sm, my_id, 0, 0, /*now=*/0);
    dnet_tick_t prev_now = 0;

    for (unsigned i = 0; i < FUZZ_ITERS_FSM; i++) {
        uint64_t st = BASE_SEED ^ salt;
        st += i;

        /* Periodically re-init to explore fresh tables + varied T3/BCT3MULT
         * (incl. 0 => defaults) without letting the table saturate forever. */
        if ((sm64(&st) % 4096u) == 0) {
            uint16_t t3 = (uint16_t)sm64(&st);
            uint16_t mult = (uint16_t)sm64(&st);
            dnet_tick_t seed_now = (dnet_tick_t)sm64(&st);
            dnet_adj_init(&sm, my_id, t3, mult, seed_now);
            prev_now = seed_now;
        }

        /* Adversarial `now`: forward jumps, backward jumps, 0, and near-UINT64_MAX
         * (listen_deadline = now + mult*adv then wraps -- unsigned, defined, must
         * not crash / must not trip UBSan). */
        dnet_tick_t now;
        switch (sm64(&st) % 5u) {
        case 0: now = 0; break;
        case 1: now = prev_now + (sm64(&st) % 64u); break;          /* small fwd */
        case 2: now = prev_now - (sm64(&st) % 64u); break;          /* backward */
        case 3: now = (dnet_tick_t)(~0ULL) - (sm64(&st) % 128u); break; /* huge */
        default: now = (dnet_tick_t)sm64(&st); break;               /* anywhere */
        }
        prev_now = now;

        /* Build an adversarial-content hello, then run it through the REAL
         * receive path (encode -> wire -> decode) before feeding the FSM -- so
         * the FSM is driven only by hellos that actually survived the decoder
         * (what a peer can send), and the endnode-decode SUCCESS path is
         * exercised ~250k times under ASan. A degenerate build could fail to
         * encode; skip only then. */
        struct dnet_endnode_hello gen = mk_fuzz_hello(&st, my_id);
        uint8_t wire[FUZZ_MAXBUF]; size_t wl = 0;
        if (dnet_hello_encode(&gen, wire, sizeof wire, &wl) != DNET_HELLO_OK)
            continue;
        struct dnet_endnode_hello h; size_t dc = 0;
        uint8_t *whb = heap_exact(wire, wl);   /* exact-size => ASan has teeth */
        int drc = dnet_hello_decode(whb, wl, &h, &dc);
        free(whb);
        if (drc != DNET_HELLO_OK) { bad++; continue; }
        if (dc > wl) bad++;

        enum dnet_adj_state out = (enum dnet_adj_state)0x7f; /* poison */
        int rc = dnet_adj_rx_hello(&sm, now, &h, &out);

        if (rc == DNET_ADJ_OK) {
            if (!valid_state(out)) { bad++; }
            if (out == DNET_ADJ_UP) reached_up++;
            /* the id we fed must now read back that same valid state */
            enum dnet_adj_state rb = dnet_adj_state_of(&sm, h.id);
            if (!valid_state(rb)) bad++;
        } else if (rc != DNET_ADJ_EFULL && rc != DNET_ADJ_EINVAL) {
            bad++;   /* stray return code */
        }

        /* Interleave the timer-expiry and cadence paths with adversarial time. */
        if ((sm64(&st) & 3u) == 0) {
            int downed = dnet_adj_tick(&sm, (dnet_tick_t)sm64(&st));
            if (downed < 0) bad++;   /* only EINVAL is negative; sm is non-NULL */
        }
        (void)dnet_adj_hello_due(&sm, now);
        (void)dnet_adj_next_hello_tick(&sm);
    }

    /* Every tracked neighbour must hold a valid enum state after the storm. */
    for (size_t k = 0; k < DNET_ADJ_MAX_NEIGHBORS; k++) {
        if (sm.nbr[k].in_use && !valid_state(sm.nbr[k].state)) bad++;
    }

    printf("  adjacency FSM fuzz: %u iters, reached UP %u times, %u invariant breaks\n",
           FUZZ_ITERS_FSM, reached_up, bad);
    CHECK(bad == 0, "adjacency FSM: fuzz clean (no crash/OOB/UB, state always a valid enum)");
    CHECK(reached_up > 0, "adjacency FSM fuzz drove neighbours to UP (two-way path exercised)");
}

/* ---- 4. POSITIVE liveness: the exact live-adjacency path vms-aac0 uses ---- */
static void liveness_two_way_up(void)
{
    static const uint8_t my_id[6]   = { 0xaa, 0x00, 0x04, 0x00, 0x01, 0x04 }; /* 1.1 */
    static const uint8_t peer_id[6] = { 0xaa, 0x00, 0x04, 0x00, 0x02, 0x04 }; /* 1.2 */

    struct dnet_adjacency sm;
    CHECK(dnet_adj_init(&sm, my_id, 0, 0, 0) == DNET_ADJ_OK, "FSM init");

    /* A one-way HELLO (peer does not name us) -> INITIALIZING. */
    struct dnet_endnode_hello h;
    memset(&h, 0, sizeof h);
    h.rflags = DNET_RFLAG_ENDNODE_HELLO; h.version = 2;
    memcpy(h.id, peer_id, 6); h.iinfo = DNET_NODETYPE_ENDNODE;
    h.blksize = 1498; h.timer = 15;
    enum dnet_adj_state s = DNET_ADJ_DOWN;
    CHECK(dnet_adj_rx_hello(&sm, 10, &h, &s) == DNET_ADJ_OK && s == DNET_ADJ_INITIALIZING,
          "one-way HELLO -> INITIALIZING");

    /* A two-way HELLO (peer names US in its neighbour field) -> UP. This is the
     * live reachability handshake the vms-aac0 lab join will exercise. */
    memcpy(h.neighbor, my_id, 6);
    CHECK(dnet_adj_rx_hello(&sm, 12, &h, &s) == DNET_ADJ_OK && s == DNET_ADJ_UP,
          "two-way HELLO (peer names us) -> UP (live-adjacency path)");
    CHECK(dnet_adj_state_of(&sm, peer_id) == DNET_ADJ_UP, "neighbour reads UP");
}

static void liveness_router_hello_roundtrip(void)
{
    struct dnet_router_hello in, out;
    memset(&in, 0, sizeof in);
    in.rflags = DNET_RFLAG_ROUTER_HELLO; in.version = 2;
    in.id[0] = 0xaa; in.id[1] = 0x00; in.id[2] = 0x04; in.id[3] = 0x00;
    in.id[4] = 0x05; in.id[5] = 0x04;
    in.iinfo = DNET_NODETYPE_L1ROUTER; in.blksize = 1498;
    in.priority = 64; in.timer = 15;
    in.elist_len = 4;
    in.elist[0] = 0xaa; in.elist[1] = 0x00; in.elist[2] = 0x04; in.elist[3] = 0x02;

    uint8_t wire[64]; size_t wl = 0;
    CHECK(dnet_router_hello_encode(&in, wire, sizeof wire, &wl) == DNET_ROUTER_HELLO_OK,
          "router-hello encodes");
    size_t consumed = 0;
    CHECK(dnet_router_hello_decode(wire, wl, &out, &consumed) == DNET_ROUTER_HELLO_OK,
          "router-hello decodes");
    CHECK(out.rflags == in.rflags && out.priority == in.priority &&
          out.timer == in.timer && out.elist_len == in.elist_len &&
          memcmp(out.id, in.id, DNET_ADDR_LEN) == 0 &&
          memcmp(out.elist, in.elist, in.elist_len) == 0,
          "router-hello round-trips encode->decode with identical fields");
}

int main(void)
{
    printf("test_dnet_routing_fuzz: DECnet routing receive-path fuzz (rd vms-aac0)\n");
    printf("  base seed = 0x%016llx (replayable); AddressSanitizer %s\n",
           (unsigned long long)BASE_SEED,
           OVMX_FUZZ_ASAN_ACTIVE ? "ACTIVE (teeth on)" : "NOT active (no teeth)");

    /* rd vms-abf: in the gated CI leg (OVMX_FUZZ_REQUIRE_SANITIZERS=1), a run
     * without ASan has no teeth -- an over-read would pass silently. Red loudly
     * instead of re-opening the crash vector unnoticed. */
    const char *require_san = getenv("OVMX_FUZZ_REQUIRE_SANITIZERS");
    if (require_san && require_san[0] && !OVMX_FUZZ_ASAN_ACTIVE) {
        fprintf(stderr,
                "test_dnet_routing_fuzz: FAIL -- OVMX_FUZZ_REQUIRE_SANITIZERS is set but "
                "this binary was built WITHOUT AddressSanitizer, so the receive-path "
                "crash-vector proof has NO TEETH. Refusing to pass toothless (rd vms-abf).\n");
        return 1;
    }

    fuzz_router_hello();
    fuzz_endnode_hello();
    fuzz_adjacency_fsm();
    liveness_two_way_up();
    liveness_router_hello_roundtrip();

    if (g_fail == 0) {
        printf("test_dnet_routing_fuzz: ALL CHECKS PASSED\n");
        return 0;
    }
    printf("test_dnet_routing_fuzz: %d CHECK(S) FAILED\n", g_fail);
    return 1;
}
