/*
 * mmk_default_rules.h - OVMX (vms-ec70) minimal compiled default-rules table.
 *
 * *** OVMX DESIGN CHOICE (clean-room, Rule 8) ***
 *
 * On OpenVMS this header is GENERATED by MMK's own GENSTRUC / MMK_COMPILE_RULES
 * build tools from mmk_default_rules_<arch>.mms (the built-in .SUFFIXES and
 * ".c.obj:" style implicit rules, whose command bodies are DCL "CC"/"LINK"
 * lines).  Those tools are themselves MMK-toolchain images with their own CLDs;
 * bringing them up on OVMX is deferred (see the vms-ec70 PR).  Until then MMK.EXE
 * ships with NO compiled-in default rules: a description file must state its
 * rules/commands explicitly (which the self-host spine's descrip.mms trees do).
 *
 * Map_Default_Rules() (default_rules.c) guards every block with *_INIT_COUNT > 0,
 * so zero counts make it install an empty suffix/symbol/rule set cleanly.
 */
#ifndef OVMX_MMK_DEFAULT_RULES_H
#define OVMX_MMK_DEFAULT_RULES_H

/* [1]-sized (ISO C forbids zero-length arrays); the counts below are 0 so the
 * single element is never touched. */
static struct SFX    sfx_init[1];
#define SFX_INIT_COUNT        0

static struct SYMBOL gsym_init[1];
#define GSYM_INIT_COUNT       0

static struct RULE   rule_init[1];
#define RULE_INIT_COUNT       0
#define RULE_INIT_COUNT_REAL  0
#define RULE_REAL_LAST_IDX    0

static struct RULE   default_rule_init;   /* .cmdque.flags == 0 -> no commands */

#endif /* OVMX_MMK_DEFAULT_RULES_H */
