#!/usr/bin/env python3
"""check_oracle_constants.py - OpenVMS constant values vs the real-node oracle (vms-619).

docs/oracle/vax73-starlet-defs/<NAME>.txt holds the `$EQU name value` lines that
`LIBRARY/MACRO/EXTRACT=$<NAME> SYS$LIBRARY:STARLET.MLB` printed on a live
OpenVMS VAX V7.3 node (the system's own library, observed -- see
docs/oracle/vax73-starlet-defs/README.md). This tool compares every NAME the
tree's headers define with a literal value against that oracle.

It is a RATCHET, not a wish: docs/oracle/constants-known-mismatch.txt lists the
names whose tree value is known to differ from the oracle (rd vms-f811). The gate
fails when
  * a tree constant differs from the oracle and is NOT on the list (a new wrong
    value), or
  * a name on the list now matches the oracle (the list is stale: delete the line).
The list can therefore only shrink.

  check_oracle_constants.py [--root=DIR]            check
  check_oracle_constants.py --write-known           (re)write the known-mismatch list
  check_oracle_constants.py --report                print every mismatch
"""
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
HEADER_DIRS = ["src/libvms/include", "src/libvms/include/vms", "src/vmsrms/include/rms", "src/vmsprocess/include/vms"]


# Structure-field offsets and sizes ($S_ $L_ $W_ $B_ $Q_ $T_ $R_ $PS_ ... ) describe a
# structure's LAYOUT, which OVMX's own headers deliberately do not mirror (struct FAB is
# not the VMS FAB). Only VALUE constants are compared: $_ item/function codes, $C_ $K_
# constants, $M_ masks and $V_ bit numbers.
_FIELD_KIND = re.compile(r"\$(S|L|W|B|Q|T|R|A|O|F|D|G|H|U|Z|P[SQHBLW]|I[HSBLWQ])_")


def _value_kind(name):
    return _FIELD_KIND.search(name) is None


def _load_dir(root, rel):
    d = {}
    for f in sorted(glob.glob(os.path.join(root, rel, "*.txt"))):
        for ln in open(f, errors="ignore"):
            m = re.match(r"\$EQU\s+(\S+)\s+(-?(?:0x)?[0-9A-Fa-f]+)\s*$", ln)
            if m and _value_kind(m.group(1)):
                try:
                    d.setdefault(m.group(1), int(m.group(2), 0) if m.group(2).lower().startswith(("0x", "-0x")) else int(m.group(2), 10))
                except ValueError:
                    pass
    return d


def oracle(root):
    """The VAX V7.3 oracle; names it does not define fall back to the Alpha V8.4
    oracle (docs/oracle/alpha84-starlet-defs). A name present on both uses the VAX value."""
    d = _load_dir(root, "docs/oracle/alpha84-starlet-defs")
    d.update(_load_dir(root, "docs/oracle/vax73-starlet-defs"))
    return d


def tree(root):
    d = {}
    for hd in HEADER_DIRS:
        for f in sorted(glob.glob(os.path.join(root, hd, "*.h"))):
            for ln in open(f, errors="ignore"):
                m = re.match(r"\s*#\s*define\s+([A-Za-z0-9_]+\$[A-Za-z0-9_$]*)\s+\(?\s*(0[xX][0-9a-fA-F]+|\d+)[uUlL]*\s*\)?\s*(?:/\*.*)?$", ln)
                if m and m.group(1) not in d:
                    d[m.group(1)] = int(m.group(2), 0)
    return d


def mismatches(root):
    o, t = oracle(root), tree(root)
    return {k: (t[k], o[k]) for k in t if k in o and t[k] != o[k]
            and (t[k] & 0xFFFFFFFF) != (o[k] & 0xFFFFFFFF)}, len(o), len(t)


def known(root):
    k = {}
    p = os.path.join(root, "docs/oracle/constants-known-mismatch.txt")
    if os.path.exists(p):
        for ln in open(p):
            ln = ln.strip()
            if ln and not ln.startswith("#"):
                k[ln.split()[0]] = ln
    return k


def main(argv):
    root = ROOT
    for a in argv:
        if a.startswith("--root="):
            root = a.split("=", 1)[1]
    mm, no, nt = mismatches(root)
    if "--report" in argv:
        for k in sorted(mm):
            print("%-28s tree=%-8d oracle=%d" % (k, mm[k][0], mm[k][1]))
        print("%d mismatches (oracle %d names, tree %d literal names)" % (len(mm), no, nt))
        return 0
    if "--write-known" in argv:
        with open(os.path.join(root, "docs/oracle/constants-known-mismatch.txt"), "w") as f:
            f.write("# Tree constants whose value differs from the OpenVMS VAX V7.3 oracle (vms-f811).\n"
                    "# Generated by tools/compat/check_oracle_constants.py --write-known; the gate\n"
                    "# tests/integration/test_oracle_constants.sh lets this list only SHRINK.\n"
                    "# format: NAME tree-value oracle-value\n")
            for k in sorted(mm):
                f.write("%s %d %d\n" % (k, mm[k][0], mm[k][1]))
        print("wrote %d known mismatches" % len(mm))
        return 0
    kn = known(root)
    bad = False
    for k in sorted(mm):
        if k not in kn:
            print("check_oracle_constants: %s = %d in the tree but %d on the VAX V7.3 oracle, and it is not a known mismatch" % (k, mm[k][0], mm[k][1]), file=sys.stderr)
            bad = True
    for k in sorted(kn):
        if k not in mm:
            print("check_oracle_constants: %s is listed as a known mismatch but now matches (or is gone) -- delete it from docs/oracle/constants-known-mismatch.txt" % k, file=sys.stderr)
            bad = True
    if bad:
        return 1
    print("oracle constants: %d tree constants checked against %d oracle names; %d known mismatches, no new ones" % (nt, no, len(kn)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
