/*
 * vms/iodef.h - I/O function codes and modifiers (vms-022).
 *
 * Generated from docs/oracle/alpha84-starlet-defs/IODEF.txt (the values an
 * OpenVMS Alpha V8.4 node defines); constants only.
 */
#ifndef __VMS_IODEF_H
#define __VMS_IODEF_H

#define IO$_NOP                      0
#define IO$_UNLOAD                   1
#define IO$_LOADMCODE                1
#define IO$_START_BUS                1
#define IO$_SEEK                     2
#define IO$_SPACEFILE                2
#define IO$_STARTMPROC               2
#define IO$_STOP_BUS                 2
#define IO$_RECAL                    3
#define IO$_DUPLEX                   3
#define IO$_STOP                     3
#define IO$_DEF_COMP                 3
#define IO$_DRVCLR                   4
#define IO$_INITIALIZE               4
#define IO$_MIMIC                    4
#define IO$_DEF_COMP_LIST            4
#define IO$_FLUSH_ERROR              4
#define IO$_RELEASE                  5
#define IO$_SETCLOCKP                5
#define IO$_START_ANALYSIS           5
#define IO$_BIND                     5
#define IO$_PATH_VERIFY              5
#define IO$_OFFSET                   6
#define IO$_ERASETAPE                6
#define IO$_STARTDATAP               6
#define IO$_STOP_ANALYSIS            6
#define IO$_UNBIND                   6
#define IO$_RETCENTER                7
#define IO$_QSTOP                    7
#define IO$_START_MONITOR            7
#define IO$_CREDISK                  7
#define IO$_LOCAL_DRAIN              7
#define IO$_PACKACK                  8
#define IO$_STOP_MONITOR             8
#define IO$_SEARCH                   9
#define IO$_SPACERECORD              9
#define IO$_READRCT                  9
#define IO$_REMDISK                  9
#define IO$_WRITECHECK               10
#define IO$_EXPORT                   10
#define IO$_WRITEPBLK                11
#define IO$_READPBLK                 12
#define IO$_WRITEHEAD                13
#define IO$_RDSTATS                  13
#define IO$_CRESHAD                  13
#define IO$_READHEAD                 14
#define IO$_ADDSHAD                  14
#define IO$_WRITETRACKD              15
#define IO$_COPYSHAD                 15
#define IO$_READTRACKD               16
#define IO$_REMSHAD                  16
#define IO$_AVAILABLE                17
#define IO$_SETPRFPATH               18
#define IO$_DISPLAY                  19
#define IO$_REMSHADMBR               20
#define IO$_DSE                      21
#define IO$_REREADN                  22
#define IO$_DISK_COPY_DATA           22
#define IO$_MOUNTSHAD                23
#define IO$_REREADP                  23
#define IO$_WHM                      23
#define IO$_AS_SETCHAR               23
#define IO$_WRITERET                 24
#define IO$_WRITECHECKH              24
#define IO$_AS_SENSECHAR             24
#define IO$_ADDSHADMBR               25
#define IO$_READPRESET               25
#define IO$_STARTSPNDL               25
#define IO$_SETCHAR                  26
#define IO$_SENSECHAR                27
#define IO$_WRITEMARK                28
#define IO$_COPYMEM                  28
#define IO$_PSXSETCHAR               28
#define IO$_WRTTMKR                  29
#define IO$_DIAGNOSE                 29
#define IO$_SHADMV                   29
#define IO$_PSXSENSECHAR             29
#define IO$_FORMAT                   30
#define IO$_CLEAN                    30
#define IO$_UPSHAD                   30
#define IO$_PHYSICAL                 31
#define IO$_WRITELBLK                32
#define IO$_READLBLK                 33
#define IO$_REWINDOFF                34
#define IO$_READRCTL                 34
#define IO$_SETMODE                  35
#define IO$_REWIND                   36
#define IO$_SKIPFILE                 37
#define IO$_PSXSETMODE               37
#define IO$_SKIPRECORD               38
#define IO$_PSXSENSEMODE             38
#define IO$_SENSEMODE                39
#define IO$_WRITEOF                  40
#define IO$_TTY_PORT_BUFIO           40
#define IO$_TTY_PORT                 41
#define IO$_FREECAP                  41
#define IO$_FLUSH                    42
#define IO$_AS_SETMODE               42
#define IO$_READLCHUNK               43
#define IO$_AS_SENSEMODE             43
#define IO$_WRITELCHUNK              44
#define IO$_LOGICAL                  47
#define IO$_WRITEVBLK                48
#define IO$_READVBLK                 49
#define IO$_ACCESS                   50
#define IO$_PSXWRITEVBLK             50
#define IO$_CREATE                   51
#define IO$_DEACCESS                 52
#define IO$_PSXREADVBLK              52
#define IO$_DELETE                   53
#define IO$_MODIFY                   54
#define IO$_NETCONTROL               54
#define IO$_READPROMPT               55
#define IO$_SETCLOCK                 55
#define IO$_AUDIO                    55
#define IO$_ACPCONTROL               56
#define IO$_STARTDATA                56
#define IO$_IOCTLV                   56
#define IO$_MANAGE                   56
#define IO$_MOUNT                    57
#define IO$_TTYREADALL               58
#define IO$_DISMOUNT                 58
#define IO$_TTYREADPALL              59
#define IO$_USBATTR                  59
#define IO$_CONINTREAD               60
#define IO$_CONINTWRITE              61
#define IO$_READDIR                  62
#define IO$_VIRTUAL                  63
#define IO$M_FCODE                   63
#define IO$M_FMODIFIERS              65472
#define IO$M_INHERLOG                2048
#define IO$M_ERASE                   1024
#define IO$M_EXFUNC                  8192
#define IO$M_DATACHECK               16384
#define IO$M_INHRETRY                32768
#define IO$M_SYNCSTS                 65536
#define IO$M_NOVCACHE                131072
#define IO$M_BUFOBJ                  262144
#define IO$M_TRUSTED                 524288
#define IO$M_FILE_FLUSH              1048576
#define IO$M_BARRIER                 2097152
#define IO$M_RAH_HINT                4194304
#define IO$M_INHSEEK                 4096
#define IO$M_READ_TO_EOF             2097152
#define IO$M_REVERSE                 64
#define IO$M_NOWAIT                  128
#define IO$M_INHEXTGAP               4096
#define IO$M_RETENSION               8192
#define IO$M_ALLOWFAST               16384
#define IO$M_MT3_DENSITY             32768
#define IO$M_MSCPMODIFS              256
#define IO$M_SHADOW                  64
#define IO$M_LOCATE                  128
#define IO$M_MSCP_FORMAT             64
#define IO$M_ALLHOSTS                64
#define IO$M_DISSOLVE                128
#define IO$M_NOCLEANUP               256
#define IO$M_SPINDOWN                64
#define IO$M_EST_COM_PATH            64
#define IO$M_LCL_SRC_UNIT            128
#define IO$M_RTN_COM_PATH            256
#define IO$M_DEALC_ALL               64
#define IO$M_DEALC_HRN               128
#define IO$M_DEALC_ENTLOC            256
#define IO$M_DECR_AFC                512
#define IO$M_READ_ALL                1024
#define IO$M_READ_HRN                2048
#define IO$M_BREAK_CONN              4096
#define IO$M_STEPOVER                64
#define IO$M_COPYOP                  256
#define IO$M_EXISTS                  64
#define IO$M_CBS                     128
#define IO$M_BOOTING                 256
#define IO$M_REQ_MINICOPY            512
#define IO$M_OPT_MINICOPY            1024
#define IO$M_NOMINICOPY              2048
#define IO$M_EXPECT_MOUNT_DONE       8192
#define IO$M_VUEX_FC                 512
#define IO$M_WRITE_SCB               512
#define IO$M_UPD_SCBLBN              8192
#define IO$M_FORCEPATH               64
#define IO$M_PREFERRED_CPU           128
#define IO$M_SYS_ASSIGNABLE          256
#define IO$M_COMMOD                  64
#define IO$M_MOVETRACKD              128
#define IO$M_DIAGNOSTIC              256
#define IO$M_SKPSECINH               512
#define IO$M_DELDATA                 64
#define IO$M_NOMRSP                  64
#define IO$M_SWAP                    256
#define IO$M_OPPOSITE                512
#define IO$M_CLSEREXCP               512
#define IO$M_CHUNKDIAG               64
#define IO$M_TBC                     1024
#define IO$M_ENAREP                  64
#define IO$M_ACCESS                  64
#define IO$M_CREATE                  128
#define IO$M_DELETE                  256
#define IO$M_MOUNT                   512
#define IO$M_DMOUNT                  1024
#define IO$M_REMOUNT                 2048
#define IO$M_MOVEFILE                4096
#define IO$M_RWSHELVED               16384
#define IO$M_SETDIR                  32768
#define IO$M_BINARY                  64
#define IO$M_PACKED                  128
#define IO$M_NOW                     64
#define IO$M_STREAM                  128
#define IO$M_READERCHECK             256
#define IO$M_WRITERCHECK             512
#define IO$M_NORSWAIT                1024
#define IO$M_MB_ROOM_NOTIFY          64
#define IO$M_READATTN                128
#define IO$M_WRTATTN                 256
#define IO$M_SETPROT                 512
#define IO$M_READERWAIT              1024
#define IO$M_WRITERWAIT              2048
#define IO$M_NOECHO                  64
#define IO$M_TIMED                   128
#define IO$M_CVTLOW                  256
#define IO$M_NOFILTR                 512
#define IO$M_DSABLMBX                1024
#define IO$M_PURGE                   2048
#define IO$M_TRMNOECHO               4096
#define IO$M_REFRESH                 8192
#define IO$M_ESCAPE                  16384
#define IO$M_EXTEND                  32768
#define IO$M_CANCTRLO                64
#define IO$M_ENABLMBX                128
#define IO$M_NOFORMAT                256
#define IO$M_BREAKTHRU               512
#define IO$M_NEWLINE                 1024
#define IO$M_TYPEAHDCNT              64
#define IO$M_MAINT                   64
#define IO$M_CTRLYAST                128
#define IO$M_CTRLCAST                256
#define IO$M_HANGUP                  512
#define IO$M_OUTBAND                 1024
#define IO$M_TT_CONNECT              2048
#define IO$M_TT_DISCON               4096
#define IO$M_TT_PROCESS              8192
#define IO$M_BRDCST                  16384
#define IO$M_LOOP                    128
#define IO$M_UNLOOP                  256
#define IO$M_LINE_OFF                512
#define IO$M_SET_MODEM               1024
#define IO$M_LINE_ON                 2048
#define IO$M_LOOP_EXT                4096
#define IO$M_AUTXOF_ENA              8192
#define IO$M_AUTXOF_DIS              16384
#define IO$M_INCLUDE                 2048
#define IO$M_TT_ABORT                4096
#define IO$M_POSIXINIT               64
#define IO$M_POSIXFLOW               128
#define IO$M_SET_POSIX               128
#define IO$M_CLEAR_POSIX             256
#define IO$M_SET_TERMIOS             512
#define IO$M_SET_PTC                 1024
#define IO$M_CLEAR_PTC               2048
#define IO$M_FLUSH_TAB               4096
#define IO$M_FLUSH_OUTPUT            8192
#define IO$M_UPDATE_PTC              16384
#define IO$M_OUT_XOFF                256
#define IO$M_OUT_XON                 512
#define IO$M_IN_XOFF                 1024
#define IO$M_IN_XON                  2048
#define IO$M_O_NONBLOCK              64
#define IO$M_INTERRUPT               64
#define IO$M_MULTIPLE                128
#define IO$M_LOCKBUF                 256
#define IO$M_NOBLOCK                 512
#define IO$M_ABORT                   256
#define IO$M_SYNCH                   512
#define IO$M_RESPONSE                64
#define IO$M_STARTUP                 64
#define IO$M_SHUTDOWN                128
#define IO$M_ATTNAST                 256
#define IO$M_CTRL                    512
#define IO$M_SET_MAC                 2048
#define IO$M_UPDATE_MAP              4096
#define IO$M_ROUTE                   8192
#define IO$M_RD_MEM                  64
#define IO$M_RD_MODEM                128
#define IO$M_RD_COUNT                256
#define IO$M_CLR_COUNT               1024
#define IO$M_SENSE_MAC               2048
#define IO$M_SHOW_MAP                4096
#define IO$M_SHOW_ROUTE              8192
#define IO$M_MORE                    64
#define IO$M_QUALIFIED               128
#define IO$M_REDIRECT                64
#define IO$M_ACCEPT                  128
#define IO$M_SETEVF                  64
#define IO$M_WORD                    64
#define IO$M_SETFNCT                 512
#define IO$M_DATAPATH                1024
#define IO$M_CYCLE                   4096
#define IO$M_RESET                   8192
#define IO$M_SETCUADR                256
#define IO$M_SETBSIZE                512
#define IO$M_SETPOOLSZ               1024
#define IO$M_SETENQCNT               2048
#define IO$M_CLEAR                   4096
#define IO$M_LPBEXT                  8192
#define IO$M_LPBINT                  16384
#define IO$M_READCSR                 32768
#define IO$M_NOCTSWAIT               64
#define IO$M_SLAVLOOP                128
#define IO$M_NODSRWAIT               256
#define IO$M_MAINTLOOP               512
#define IO$M_LASTBLOCK               1024
#define IO$M_INTCLOCK                4096
#define IO$M_LT_CONNECT              64
#define IO$M_LT_DISCON               128
#define IO$M_LT_READPORT             256
#define IO$M_LT_MAP_PORT             512
#define IO$M_LT_RATING               1024
#define IO$M_LT_SOL_INFO             2048
#define IO$M_LT_RCV_INFO             4096
#define IO$M_LT_SETMODE              8192
#define IO$M_LT_SENSEMODE            16384
#define IO$M_LT_QUE_CHG_NOTIF        32768
#define IO$M_LT_MAP_FILLER           1
#define IO$M_LT_MAP_NODNAM           2
#define IO$M_LT_MAP_PORNAM           4
#define IO$M_LT_MAP_SRVNAM           8
#define IO$M_LT_MAP_LNKNAM           16
#define IO$M_LT_MAP_NETADR           32
#define IO$M_FLUSH                   64
#define IO$M_WRITE_BARRIER           128
#define IO$M_MKFILL1                 64
#define IO$M_ALLOWFAST_NEVER         128
#define IO$M_ALLOWFAST_PER_IO        256
#define IO$M_ALLOWFAST_ALWAYS        512
#define IO$M_ADD                     64
#define IO$M_IDSTRING                64
#define IO$M_SERIALNUM               128
#define IO$M_BYPASS_VALID_CHK        128

#endif /* __VMS_IODEF_H */
