#!/bin/bash
# test_release_e2e.sh - the release path: boot -> provision -> boot (vms-9b7)
#
# =============================================================================
# WHY THIS TEST EXISTS
# =============================================================================
# An operator hit "%OVMX-F-EXECINIT, no SYSTEM record in SYS$SYSTEM:SYSUAF.DAT"
# on the release path -- initial boot, then a provisioning step, then a new
# boot -- and NO COMMITTED TEST COVERED THAT PATH. tests/qemu/test_persistent_
# boot.sh boots the same disk three times but never CHANGES SYSUAF between
# boots, so a system whose authorization file is edited (which is the entire
# point of having one) was untested end to end. That gap is why the failure
# reached a human instead of CI.
#
# =============================================================================
# WHAT IT DRIVES, AND WHY IT IS NOT A MUTATION TEST
# =============================================================================
# The fault is injected THROUGH THE FILE, by a real SYSTEM session using real
# DCL file I/O (OPEN/WRITE ... WRITE ... CLOSE) against the real
# SYS$SYSTEM:SYSUAF.DAT on the real installed system disk. No source is edited,
# no function is renamed or wrapped, and the reader under test is the one the
# boot actually runs. What is poisoned is the input the boot reads.
#
# THE VARIABLE IS THE POSITION OF THE SIXTH FIELD SEPARATOR, not the write path
# and not the length as such. Four cases run:
#
#   short       103-byte SYSTEM row, sixth separator at  99  -- CONTROL, must boot
#   inwin       502-byte SYSTEM row, sixth separator at 387  -- CONTROL, must boot
#   longrow     675-byte SYSTEM row, sixth separator at 560  -- past 511, must boot
#   norecord    NO SYSTEM row at all                         -- must HALT
#
# A fifth case (poisoned_uic, vms-a17e) is not about the sixth separator at
# all -- see its own comment below -- and proves identity establishment reads
# SYSUAF zero times: a SYSTEM row carrying a UIC and privilege string that are
# NOT [1,4]/ALL must still produce "[1,4] established by the executive",
# because the executive constructs that identity from its own constant now,
# never from this file.
#
# All four are written by the same DCL session through the same commands into
# the same file on the same rig. If the rig itself broke SYSUAF, "short" would
# fail too -- and the whole point of running it is that it does not. And if the
# rig could not distinguish a broken system from a working one, "norecord"
# would pass anyway -- which is why it is here.
#
# MEASURED BOTH WAYS with this exact script, 2026-08-07:
#
#   image built from the UNFIXED tree (origin/main d7a404e):
#       RESULTS: 21 passed, 3 failed   (exit 1)
#         FAIL: longrow boot 2: reaches the login prompt
#         FAIL: longrow boot 2: NO '%OVMX-F-EXECINIT, no SYSTEM record' halt
#         FAIL: longrow boot 2: SYSTEM [1,4] established by the executive
#   image built from the FIXED tree:
#       RESULTS: 24 passed, 0 failed   (exit 0)
#
# Note that "norecord" PASSES on the unfixed tree too -- the fail-stop worked
# there, in PID 1. That is the point of keeping it: it shows the 3 failures
# above are this test discriminating, not this test being broken.
#
# Per case, on the unfixed tree:
#
#   short    -> boot 2 GREEN  (%OVMX-I-EXEC, system identity SYSTEM [1,4] ...)
#   inwin    -> boot 2 GREEN
#   longrow  -> boot 2:
#                %STARTUP-I-SYSBOOT, system disk detected, skipping install
#                %OVMX-F-EXECINIT, no SYSTEM record in SYS$SYSTEM:SYSUAF.DAT
#                %OVMX-I-EXECINIT, the system process has no authorized identity
#                [    2.925907] reboot: Power down
#
# That is the operator's halt, reproduced, with two controls that isolate it to
# the one variable. On the fixed tree all cases hold, because PID 1 no longer
# parses SYSUAF at all and the one remaining reader reports an over-length
# record instead of silently shortening it.
#
# =============================================================================
# DO NOT EDIT THIS FILE WHILE A RUN IS IN FLIGHT. bash reads a script by BYTE
# OFFSET as it executes, and this file is bind-mounted read-only into the
# container that is running it -- so an edit that changes the file's length
# makes bash resume at the wrong offset and RE-EXECUTE a case. Observed
# directly while this test was being written: an edit to the comment block
# above caused the `longrow` case to run twice, in two separate containers,
# deterministically. The per-case output stayed correct; the run as a whole
# was not a measurement. Finish the run, then edit.
#
# =============================================================================
# THE WRITEBACK TRAP -- READ THIS BEFORE CHANGING THE TIMING
# =============================================================================
# The first version of this rig produced a FALSE reproduction: every case
# halted, including the control. The cause was not SYSUAF -- it was that the
# guest's dirty pages had not been written back when qemu was killed, so boot 2
# read the pre-edit file (and, on a blank disk, no file at all). Linux's
# default dirty_expire_centisecs is 30 seconds. SETTLE_SECS below is what makes
# the edit real; shortening it silently turns this test into one that passes
# whatever the code does. (Related but distinct: qemu's own writeback cache
# across separate container invocations -- cache=writethrough here.)
#
# Usage:
#   docker build -f distro/Dockerfile.bootable -t ovmx-boot .
#   docker run --rm -v $PWD/tests/qemu/test_release_e2e.sh:/test.sh:ro \
#       --entrypoint bash ovmx-boot /test.sh
#
# Exit 0 = all cases boot green, 1 = a case failed.

set -uo pipefail

BOOT_TIMEOUT=300
SETTLE_SECS="${SETTLE_SECS:-60}"     # see THE WRITEBACK TRAP above
KERNEL=/boot/vmlinuz
INITRD=/boot/initramfs-ovmx.cpio.gz
# The PRE-INSTALLED distribution disk (vms-8ab), mastered at BUILD time. Since
# PID 1 no longer installs on a blank disk (vms-2f0, operator ruling 2026-08-10
# "STRIP ALL OF IT"), every case here SEEDS its disk from this image -- a plain
# byte copy -- instead of truncating a blank one. Boot 1 then boots an already
# installed system and a real SYSTEM session edits SYS$SYSTEM:SYSUAF.DAT on it,
# exactly as before; only the way the disk comes to exist changed.
DISTRIB_IMG=/boot/ovmx-distrib.img
ARCH=$(uname -m)

if [ ! -f "$DISTRIB_IMG" ]; then
    echo "FAIL: $DISTRIB_IMG is missing — the mastering stage did not run;"
    echo "      a stripped PID 1 cannot install a blank disk, so this test needs it."
    exit 1
fi

if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    QEMU=qemu-system-aarch64
    MACHINE="-machine virt -cpu cortex-a57"
    CONSOLE="console=ttyAMA0"
else
    QEMU=qemu-system-x86_64
    MACHINE=""
    CONSOLE="console=ttyS0"
fi

PASS=0
FAIL=0

record() {
    local desc="$1" rc="$2"
    if [ "$rc" -eq 0 ]; then
        echo "  PASS: $desc"; PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc"; FAIL=$((FAIL + 1))
    fi
}

# The SYSTEM password hash the shipped SYSUAF carries for MANAGER (vms-72c).
# Kept byte-identical so the poisoned rows still authenticate -- a row that
# could not log in would confound "the boot found SYSTEM" with "the session
# worked".
HASH=36a708df24b4751520ee64bba2d92167294acbb8f8fbfc3a120fb75323e9739b

# Build a SYSTEM row whose sixth separator lands at a chosen offset.
#   $1 = DEFAULT_DIR padding target, $2 = FLAGS length
make_system_row() {
    local ddlen="$1" fllen="$2"
    local dd="SYS\$SYSDEVICE:[SYSMGR"
    while [ ${#dd} -lt $((ddlen - 1)) ]; do dd="${dd}D"; done
    dd="${dd}]"
    local fl=""
    local i=0
    while [ $i -lt "$fllen" ]; do fl="${fl}F"; i=$((i + 1)); done
    # A real, fully expanded privilege list -- the shape the field grows into.
    local pv="TMPMBX,NETMBX,OPER,SYSPRV,BYPASS,SETPRV,CMKRNL,CMEXEC,SYSNAM,GRPNAM,DETACH,SETPRI,ALTPRI,WORLD,GROUP,LOG_IO,PHY_IO"
    printf 'SYSTEM|%s|1|4|%s|%s|%s' "$HASH" "$dd" "$fl" "$pv"
}

sixth_sep_offset() {
    printf '%s' "$1" | awk '{
        n=0
        for (i = 1; i <= length($0); i++)
            if (substr($0, i, 1) == "|") { n++; if (n == 6) { print i-1; exit } }
        print -1
    }'
}

OTHER_ROWS=(
 "OPERATOR||1|6|SYS\$SYSDEVICE:[SYSMGR]||OPER,SYSPRV,TMPMBX,NETMBX"
 "DEFAULT||200|200|SYS\$SYSDEVICE:[USERS.DEFAULT]||TMPMBX,NETMBX"
 "GUEST|16ceb2796ccd9d52d4f2a92134ef9ecfeb8f016150a82d36b299d09d5b9963f0|200|201|SYS\$SYSDEVICE:[USERS.GUEST]||TMPMBX"
 "USER1||200|202|SYS\$SYSDEVICE:[USERS.USER1]||TMPMBX,NETMBX"
 "USER2||200|203|SYS\$SYSDEVICE:[USERS.USER2]||TMPMBX,NETMBX"
)

# ---------------------------------------------------------------------------
# One case: pre-installed disk -> boot -> edit SYSUAF from a SYSTEM session
#           -> reboot -> the system must come up with an identity.
# ---------------------------------------------------------------------------
# $3 = "up" (must boot) or "halt" (must fail-stop with the EXECINIT message).
run_case() {
    # uic (5th arg) is the SYSUAF-FILE-CONTENT UIC this case's row carries --
    # used ONLY by the sanity check a few lines down that the DCL WRITE
    # actually landed in the file. It defaults to "1|4" because that is what
    # every case except poisoned_uic (vms-a17e) writes. It is NOT a claim
    # about what identity the boot ends up with: see that check's own
    # comment for why the two can legitimately differ.
    local tag="$1" system_row="$2" expect="${3:-up}" uic="${4:-1|4}"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    if [ -n "$system_row" ]; then
        echo "CASE $tag: SYSTEM row ${#system_row} bytes, sixth separator at $(sixth_sep_offset "$system_row"), expect=$expect"
    else
        echo "CASE $tag: NO SYSTEM ROW AT ALL, expect=$expect"
    fi
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    # vms-2213: OPA0: LOGINOUT waits for the operator RETURN before Username:; a
    # lone CR at t=0 is lost (serial not up yet), so feed one per second until
    # the prompt appears. Bounded.
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: install ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    # --- Provision: a real SYSTEM session edits the real SYSUAF ---
    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    send 'OPEN/WRITE UF SYS$SYSTEM:SYSUAF.DAT'; sleep 1
    if [ -n "$system_row" ]; then
        send "WRITE UF \"$system_row\""; sleep 1
    fi
    for row in "${OTHER_ROWS[@]}"; do
        send "WRITE UF \"$row\""; sleep 1
    done
    send 'CLOSE UF'; sleep 2
    send 'TYPE SYS$SYSTEM:SYSUAF.DAT'; sleep 3

    # The edit must actually be in the file this session can read, or the rest
    # of the case is measuring nothing. Checks for THIS CASE'S OWN uic (see
    # the "uic" parameter comment above) -- poisoned_uic's row genuinely
    # contains "50|50", not "1|4", and grepping the wrong pair here would
    # fail even though the poison landed exactly as intended.
    if [ -n "$system_row" ]; then
        if grep -qF "SYSTEM|$HASH|$uic|" "$log1"; then rc=0; else rc=1; fi
        record "$tag boot 1: the edited SYSTEM row is readable in-session" "$rc"
    else
        if grep -qF "OPERATOR||1|6|" "$log1"; then rc=0; else rc=1; fi
        record "$tag boot 1: SYSUAF was rewritten without a SYSTEM row" "$rc"
    fi

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: the boot that has to read what was written ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    if [ "$expect" = "halt" ]; then
        # NEGATIVE CONTROL. Proves this whole rig can still go RED, and proves
        # the fail-stop SURVIVED being moved out of PID 1 into PROVISION.EXE,
        # and then survived a second move (vms-a17e): identity establishment
        # no longer reads SYSUAF at all (vms_kif_establish_system() constructs
        # SYSTEM's identity as an executive constant regardless of what SYSUAF
        # contains), so this halt no longer comes from a failed identity read
        # -- it rides provision_home_directories()'s SYSUAF walk instead,
        # which is why the message changed from "no SYSTEM record" /
        # "the system process has no authorized identity" to the text below.
        # A fail-stop that was relocated and never fired again is a fail-stop
        # that was deleted (Rule 10: the condition is made unreachable, and it
        # only stays unreachable if entering it still stops the system).
        if waitfor '%OVMX-F-EXECINIT, no SYSTEM account' 120 "$log2"; then
            rc=0
        else
            rc=1
        fi
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
        record "$tag boot 2: HALTS with '%OVMX-F-EXECINIT, no SYSTEM account'" "$rc"

        if grep -qF '%OVMX-I-EXECINIT, no session could ever authenticate as SYSTEM' "$log2"; then
            rc=0
        else
            rc=1
        fi
        record "$tag boot 2: the detail line is PROVISION.EXE's SYSTEM-account continuity check" "$rc"

        # ...and it must NOT reach a login prompt. A system with no identity
        # that hands out a console is the exact thing the halt exists to stop.
        if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
        record "$tag boot 2: no login prompt on a system with no identity" "$rc"

        if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
        return
    fi

    wake_login "$log2"
    if waitfor 'Username:' 120 "$log2"; then rc=0; else rc=1; fi
    record "$tag boot 2: reaches the login prompt" "$rc"

    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # THE ASSERTION THE OPERATOR'S FAILURE WAS. Whole-log grep is safe: this is
    # a boot-time diagnostic printed before any prompt exists, so nothing this
    # script typed can have produced it.
    if grep -qF '%OVMX-F-EXECINIT, no SYSTEM account' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: NO '%OVMX-F-EXECINIT, no SYSTEM account' halt" "$rc"

    # And the positive half: an identity was actually established, with the
    # right values. Asserting only the absence of the halt would pass on a boot
    # that never got as far as trying.
    if grep -qF 'system identity SYSTEM [1,4] established by the executive' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: SYSTEM [1,4] established by the executive" "$rc"

    if [ "$rc" -ne 0 ] || grep -qF '%OVMX-F-EXECINIT' "$log2"; then
        echo "--- $tag boot 2 log ---"
        cat "$log2"
    fi
}

# ---------------------------------------------------------------------------
# NEGATIVE CONTROL 2: the startup process itself goes missing (vms-56c).
#
# PROVISION.EXE is boot-critical -- PID 1 stages it off the ODS-2 volume over
# the ACP and forks it as the startup process. If the image is absent the system
# has no way to acquire an identity, so PID 1 must FAIL-STOP -- never fall
# through to a login prompt on a system with no identity.
#
# vms-0a5: with DELETE now $ERASEing on the volume over the ACP (IO$_DELETE), the
# absent image is caught at boot-image staging (ovmx_init.c stage_boot_images(),
# SYSINIT) -- the earliest honest point, before the startup process is even
# forked -- and halts with the SYSINIT staging message. Asserting that specific
# message proves the mandatory-image staging guard fires and is not some other
# halt in disguise. (run_startup()'s later stat() guard remains the backstop for
# a staged copy that vanishes, and for the NetBSD-vax substrate that does not
# stage; it just is not the one that fires when the volume file is gone.)
#
# Injected THROUGH THE FILE, like every other case: a real SYSTEM session
# deletes the real image off the installed disk with DCL DELETE. No source is
# edited. If the delete did not land on the volume, boot 2 comes up and the halt
# assertion below fails -- so this case cannot false-pass.
#
# (The other fatal run_startup() path -- PROVISION.EXE activates but the
# executive REFUSES setident -- is caught by the same function at its waitpid
# nonzero-status branch, but is not injectable through the file from a session;
# it is left to inspection here rather than claimed as covered.)
# ---------------------------------------------------------------------------
run_provision_missing_case() {
    local tag="noprovision"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    echo "CASE $tag: SYSTEM deletes SYS\$SYSTEM:PROVISION.EXE, expect=halt"
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    # vms-2213: OPA0: LOGINOUT waits for the operator RETURN before Username:; a
    # lone CR at t=0 is lost (serial not up yet), so feed one per second until
    # the prompt appears. Bounded.
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: install, then delete the startup image off the disk ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    # An explicit version (here ;* = all versions) is REQUIRED on DELETE --
    # a bare "DELETE SYS$SYSTEM:PROVISION.EXE" is refused with
    # "%DELETE-E-DELVER, explicit version number or wild card required"
    # (authentic VMS, VSI OpenVMS DCL Dictionary, DELETE; landed in vms-1c6
    # #478). Without the ;* this delete never lands, PROVISION.EXE survives,
    # and boot 2 comes up instead of halting -- the exact false-negative this
    # case exists to catch.
    send 'DELETE/LOG SYS$SYSTEM:PROVISION.EXE;*'; sleep 2
    send 'DIRECTORY SYS$SYSTEM:PROVISION.EXE'; sleep 3

    # The delete must actually have landed, or boot 2 measures nothing. DELETE
    # /LOG prints the authentic '%DELETE-I-FILDEL, <spec> deleted' on success
    # (VSI OpenVMS DCL Dictionary, DELETE/LOG; vms-1c6 #478 corrected this from
    # the earlier non-authentic '%DELETE-S-DELETED'); a delete that found no
    # file prints '%RMS-E-FNF' / '%DELETE-W-SEARCHFAIL' instead and this check
    # goes red rather than silently measuring an intact disk.
    if grep -qiE '%DELETE-I-FILDEL|%DELETE-S-DELETED' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: PROVISION.EXE deleted off the disk" "$rc"

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: no startup image on disk -> PID 1 must fail-stop ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    # Whole-log grep is safe: a boot-time diagnostic printed before any prompt
    # exists, so nothing this script typed can have produced it.
    #
    # vms-0a5: DELETE now $ERASEs PROVISION.EXE off the ODS-2 VOLUME over the ACP
    # (IO$_DELETE), not a /vms passthrough copy the booted system never reads. So
    # the missing image is caught at the EARLIER, more honest point: PID 1 stages
    # the mandatory boot images off the volume over the ACP in SYSINIT
    # (stage_boot_images) BEFORE it ever forks the startup process, so the read
    # of the now-absent PROVISION.EXE fails there and fail-stops with the SYSINIT
    # staging halt rather than run_startup()'s later stat() guard. Both are honest
    # fail-stops before any login; landing the delete at the ACP layer is exactly
    # what moves the catch earlier.
    if waitfor '%OVMX-F-SYSINIT, boot-image staging failed' 120 "$log2"; then
        rc=0
    else
        rc=1
    fi
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
    record "$tag boot 2: HALTS at boot-image staging (PROVISION.EXE gone off the volume)" "$rc"

    if grep -qF 'SYS$SYSTEM:PROVISION.EXE could not be read from the ODS-2 volume over the ACP' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: the detail line names PROVISION.EXE unreadable over the ACP" "$rc"

    # ...and it must NOT reach a login prompt.
    if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: no login prompt on a system with no startup image" "$rc"

    if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
}

# ---------------------------------------------------------------------------
# NEGATIVE CONTROL: SYSUAF loses its SYSTEM account (vms-0a5).
#
# THE AUTHENTIC MECHANISM. SYSUAF.DAT is an RMS INDEXED file of binary $UAFDEF
# records, and the AUTHORIZE utility is the supported interface that removes an
# account from it -- it $DELETEs the record and writes the indexed file back
# (VSI OpenVMS Guide to System Security; AUTHORIZE). DCL OPEN/WRITE cannot edit
# SYSUAF: OPEN/WRITE CREATES A NEW SEQUENTIAL VERSION and never rewrites the
# indexed file LOGINOUT / PROVISION read, so an OPEN/WRITE "edit" of SYSUAF is
# not a VMS operation that persists to the account database. That is exactly why
# the write->read round-trip was never exercised before this item: the earlier
# form of this case wrote a sequential text version that the next boot's binary
# reader ($UAFDEF, ovmx_sysuaf_enum over the ACP) never read, so removing the
# SYSTEM row "in the file" changed nothing PROVISION saw and the system did not
# halt (the false pass this item closes).
#
# So this case mutates through AUTHORIZE: RUN SYS$SYSTEM:AUTHORIZE, REMOVE
# SYSTEM. On EXIT, AUTHORIZE authors a fresh versioned $UAFDEF indexed file over
# the Files-11 ODS-2 ACP (ovmx_sysuaf_write_all -> IO$_CREATE), which is EXACTLY
# the file PROVISION.EXE reads on the next boot (ovmx_sysuaf_enum over the same
# ACP). The removal therefore GENUINELY persists and is read back -- a real
# write->read round-trip, no executive-constant shortcut. With no SYSTEM row
# anywhere in SYSUAF, no session could ever authenticate as SYSTEM, so
# PROVISION.EXE fail-stops (provision_home_directories()'s account-provisioning
# walk recognises it never saw a SYSTEM row) and the system never reaches a
# login prompt.
# ---------------------------------------------------------------------------
run_norecord_case() {
    local tag="norecord"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    echo "CASE $tag: AUTHORIZE REMOVE SYSTEM (binary indexed SYSUAF), expect=halt"
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: log in as SYSTEM, REMOVE the SYSTEM account via AUTHORIZE ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    # AUTHORIZE over the interactive terminal: a RUN'd image's SYS$INPUT is the
    # terminal here (not a procedure data block), so UAF> reads what we type.
    # This is the "operator types at UAF>" shape, which works interactively even
    # though it cannot work inside a command procedure (OVMX$INSTALL.COM's note).
    send 'RUN SYS$SYSTEM:AUTHORIZE.EXE'; sleep 3
    if waitfor 'UAF>' 30 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE starts (UAF> prompt)" "$rc"
    send 'REMOVE SYSTEM'; sleep 2
    send 'Y'; sleep 2                 # confirm the REMOVE prompt
    send 'EXIT'; sleep 3              # EXIT triggers save_sysuaf -> binary write
    send 'SHOW TIME'; sleep 2         # back at DCL: a marker the RUN returned

    # The REMOVE and the on-exit binary write must both have reported success
    # in-session, or the rest of the case is measuring nothing.
    if grep -qF '%UAF-S-REMMSG' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE reports the SYSTEM record removed" "$rc"
    if grep -qF '%UAF-I-SAVED' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE writes the binary SYSUAF back on exit" "$rc"

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: PROVISION reads the binary SYSUAF; no SYSTEM row -> fail-stop ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    # Whole-log grep is safe: a boot-time diagnostic printed before any prompt
    # exists, so nothing this script typed can have produced it.
    if waitfor '%OVMX-F-EXECINIT, no SYSTEM account' 120 "$log2"; then rc=0; else rc=1; fi
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
    record "$tag boot 2: HALTS with '%OVMX-F-EXECINIT, no SYSTEM account'" "$rc"

    if grep -qF '%OVMX-I-EXECINIT, no session could ever authenticate as SYSTEM' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: the detail line is PROVISION.EXE's SYSTEM-account continuity check" "$rc"

    # ...and it must NOT reach a login prompt. A system with no SYSTEM account
    # that hands out a console is the exact thing the halt exists to stop.
    if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: no login prompt on a system with no SYSTEM account" "$rc"

    if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
}

echo "=== OVMX release e2e: boot -> provision -> boot (vms-9b7) ==="
echo "Architecture: $ARCH   QEMU: $QEMU"

# CONTROL 1 -- the shipped row, written by the same path. Proves the rig's
# edit mechanism does not itself break SYSUAF.
run_case short  "SYSTEM|$HASH|1|4|SYS\$SYSDEVICE:[SYSMGR]||ALL"

# CONTROL 2 -- a long row whose sixth separator is still INSIDE the 512-byte
# window the deleted readers used. Isolates the variable to the separator's
# position rather than to the row's length.
run_case inwin  "$(make_system_row 247 63)"

# THE CASE. Sixth separator past byte 511: on the unfixed tree this halted the
# boot; here it must not.
run_case longrow "$(make_system_row 420 63)" up

# CASE 5 (vms-a17e) -- THE ZERO-SYSUAF-READS-FOR-IDENTITY PROOF. This row
# names UIC [50,50] and PRIVILEGES=NONE for the SYSTEM account -- neither
# [1,4] nor ALL. Before vms-a17e this would have produced
# "system identity SYSTEM [62,62] established by the executive" (50 decimal
# is 62 octal) with no enforced privileges beyond the CAP_SYS_ADMIN default,
# because PROVISION.EXE read exactly these two fields out of this row and
# handed them to VMS_IOCTL_SETIDENT. After vms-a17e, vms_kif_establish_system()
# takes no username/uic/privs arguments at all -- SYSTEM/[1,4]/ALL are
# vms.ko's own VMS_SYSTEM_UIC / VMS_PRV_M_SYSTEM_ALL constants (vms_internal.h)
# -- so [1,4] MUST still appear, proving the poisoned UIC in this file was
# never read to construct it. Same HASH as every other case, so login still
# succeeds; only the UIC/privileges fields are wrong on purpose.
#
# WHAT THIS DOES *NOT* CLAIM, and why the boot-1 "row is readable in-session"
# sanity check below correctly reports [50,50] rather than [1,4]. There are
# TWO identities in this boot, established by two DIFFERENT mechanisms, and
# vms-a17e touches only one of them:
#
#   the STARTUP process (PROVISION.EXE, execs into STARTUP.COM/
#   SYSTARTUP_VMS.COM)  -- identity from vms_kif_establish_system(), an
#   executive CONSTANT, independent of SYSUAF by design (this item).
#
#   the INTERACTIVE session opened by typing SYSTEM/MANAGER at the login
#   prompt below -- identity from tools/vms_login.c (LOGINOUT), which reads
#   SYSUAF's SYSTEM row and calls VMS_IOCTL_SETIDENT with WHATEVER uic that
#   row names. LOGINOUT-reads-SYSUAF is correct, unmodified VMS behaviour
#   ("LOGINOUT is SYSUAF's FIRST reader") and is exactly what this item's
#   own goal statement asks for -- it would be a REGRESSION for LOGINOUT to
#   ignore this file. So a real interactive SYSTEM/MANAGER session against
#   this poisoned row genuinely authenticates as UIC [50,50]; that is not
#   probed here because the boot process's identity, not the login
#   session's, is this item's whole scope.
#
# So the "$uic" argument below (used only by the file-landed sanity check,
# not by any identity assertion) is 50|50 -- the actual, correctly-poisoned
# content of the file -- while the SEPARATE "SYSTEM [1,4] established by the
# executive" assertion in the shared "up" path a few lines down is the one
# that has to stay [1,4] regardless. Confirmed on a real boot: it does.
run_case poisoned_uic "SYSTEM|$HASH|50|50|SYS\$SYSDEVICE:[SYSMGR]||NONE" up "50|50"

# NEGATIVE CONTROL. SYSUAF with NO SYSTEM row at all -- a condition VMS is never
# in, which OVMX therefore makes unreachable rather than handles (Rule 10). This
# must still stop the system, from its home in PROVISION.EXE. Without this case
# the four "up" cases above are all "did not halt" assertions with nothing
# showing they could ever have halted.
#
# vms-0a5: this case now removes the SYSTEM account through AUTHORIZE (which
# writes the binary indexed SYSUAF back over the ACP), the authentic mechanism,
# so the halt is driven by a write that GENUINELY persisted to the file
# PROVISION reads -- see run_norecord_case's header. The functional guarantee it
# proves -- no SYSTEM account means no login prompt, ever -- is unchanged; the
# path to it is now a real write->read round-trip rather than a text write the
# reader ignored.
run_norecord_case

# NEGATIVE CONTROL 2 (vms-56c, vms-0a5). The startup process image itself is
# deleted off the disk from a SYSTEM session -- over the ACP, so it leaves the
# ODS-2 volume, not just a passthrough copy. PID 1 must fail-stop at boot-image
# staging, proving the mandatory-image guard fires and that the boot-critical
# image is not a silently-skippable step.
run_provision_missing_case

echo ""
echo "=========================================="
echo "  RESULTS: $PASS passed, $FAIL failed"
echo "=========================================="
[ "$FAIL" -eq 0 ] || exit 1
echo "  ALL RELEASE E2E CHECKS PASSED"
