#!/bin/bash
# test_release_e2e.sh - the release path: boot -> provision -> boot (vms-9b7)
#
# =============================================================================
# WHY THIS TEST EXISTS
# =============================================================================
# An operator hit "%OVMX-F-EXECINIT, no SYSTEM record in SYS$SYSTEM:SYSUAF.DAT"
# on the release path -- initial boot, then a provisioning step, then a new
# boot -- and NO COMMITTED TEST COVERED THAT PATH. tests/qemu/test_persistent_
# boot.sh boots the same disk three times but never CHANGES SYSUAF between
# boots, so a system whose authorization file is edited (which is the entire
# point of having one) was untested end to end. That gap is why the failure
# reached a human instead of CI.
#
# =============================================================================
# WHAT IT DRIVES, AND WHY IT IS NOT A MUTATION TEST
# =============================================================================
# Each case is injected THROUGH THE FILE, by a real SYSTEM session running the
# real AUTHORIZE utility (or DCL DELETE) against the real system disk. No source
# is edited, no function is renamed or wrapped, and the reader under test is the
# one the boot actually runs. What changes is the on-disk state the boot reads.
#
# THE MECHANISM IS AUTHORIZE, THE SUPPORTED SYSUAF EDITOR. SYSUAF.DAT is an RMS
# INDEXED file of binary $UAFDEF records; the only thing that persists an account
# change to the file PROVISION/LOGINOUT read is AUTHORIZE, which $DELETEs/$PUTs
# records and writes the indexed file back over the Files-11 ODS-2 ACP
# (ovmx_sysuaf_write_all). DCL OPEN/WRITE of SYS$SYSTEM:SYSUAF.DAT is NOT a
# SYSUAF edit: it $CREATEs a sequential TEXT version, and once the mastered
# system disk carries the SYS$SPECIFIC per-root [SYS0.SYSEXE] (vms-f05), a create
# through the SYS$SYSTEM: search list lands that text file in the PRIMARY member
# and SHADOWS the binary indexed SYSUAF the common member holds -- so the next
# boot's PROVISION opens the shadow, cannot bind it as Prolog-3, and halts "no
# SYSTEM account". Earlier forms of the positive cases used OPEN/WRITE and only
# "passed" while the create silently FAILED (no primary-member directory before
# vms-f05); the SYS$SPECIFIC dirs exposed that false pass, and this rig now edits
# every case through AUTHORIZE -- a genuine write->read round-trip (vms-persistboot,
# completing the vms-0a5/088e14bc conversion the norecord case started).
#
# Six cases run:
#
#   short         AUTHORIZE MODIFY SYSTEM (UIC [1,4])       -- CONTROL, must boot
#   inwin         AUTHORIZE MODIFY SYSTEM (UIC [1,4])       -- CONTROL, must boot
#   longrow       AUTHORIZE MODIFY SYSTEM (UIC [1,4])       -- CONTROL, must boot
#   poisoned_uic  AUTHORIZE MODIFY SYSTEM (UIC != [1,4])    -- must boot [1,4]
#   norecord      AUTHORIZE REMOVE SYSTEM                   -- must HALT
#   noprovision   DELETE SYS$SYSTEM:PROVISION.EXE           -- must HALT
#
# poisoned_uic (vms-a17e) proves identity establishment reads SYSUAF zero times:
# a SYSTEM account whose stored UIC is NOT [1,4] must still produce "[1,4]
# established by the executive", because the executive constructs that identity
# from its own constant now, never from this file.
#
# The three MODIFY controls each run an independent boot -> edit -> boot cycle:
# if the rig itself broke SYSUAF they would fail too, and the whole point of
# running them is that they do not. norecord/noprovision prove the rig can still
# go RED, so the "up" cases are "did boot", not "could never have halted". (The
# short/inwin/longrow triplet once varied the sixth field-separator position to
# probe a 512-byte buffer in the retired SYSUAF TEXT parser; that parser is gone
# -- PID 1 reads no SYSUAF and the binary $UAFDEF records are fixed-size -- so
# the three are now equivalent, kept as regression breadth over the live path.)
#
# =============================================================================
# DO NOT EDIT THIS FILE WHILE A RUN IS IN FLIGHT. bash reads a script by BYTE
# OFFSET as it executes, and this file is bind-mounted read-only into the
# container that is running it -- so an edit that changes the file's length
# makes bash resume at the wrong offset and RE-EXECUTE a case. Observed
# directly while this test was being written: an edit to the comment block
# above caused the `longrow` case to run twice, in two separate containers,
# deterministically. The per-case output stayed correct; the run as a whole
# was not a measurement. Finish the run, then edit.
#
# =============================================================================
# THE WRITEBACK TRAP -- READ THIS BEFORE CHANGING THE TIMING
# =============================================================================
# The first version of this rig produced a FALSE reproduction: every case
# halted, including the control. The cause was not SYSUAF -- it was that the
# guest's dirty pages had not been written back when qemu was killed, so boot 2
# read the pre-edit file (and, on a blank disk, no file at all). Linux's
# default dirty_expire_centisecs is 30 seconds. SETTLE_SECS below is what makes
# the edit real; shortening it silently turns this test into one that passes
# whatever the code does. (Related but distinct: qemu's own writeback cache
# across separate container invocations -- cache=writethrough here.)
#
# Usage:
#   docker build -f distro/Dockerfile.bootable -t ovmx-boot .
#   docker run --rm -v $PWD/tests/qemu/test_release_e2e.sh:/test.sh:ro \
#       --entrypoint bash ovmx-boot /test.sh
#
# Exit 0 = all cases boot green, 1 = a case failed.

set -uo pipefail

BOOT_TIMEOUT=300
SETTLE_SECS="${SETTLE_SECS:-60}"     # see THE WRITEBACK TRAP above
KERNEL=/boot/vmlinuz
INITRD=/boot/initramfs-ovmx.cpio.gz
# The PRE-INSTALLED distribution disk (vms-8ab), mastered at BUILD time. Since
# PID 1 no longer installs on a blank disk (vms-2f0, operator ruling 2026-08-10
# "STRIP ALL OF IT"), every case here SEEDS its disk from this image -- a plain
# byte copy -- instead of truncating a blank one. Boot 1 then boots an already
# installed system and a real SYSTEM session edits SYS$SYSTEM:SYSUAF.DAT on it,
# exactly as before; only the way the disk comes to exist changed.
DISTRIB_IMG=/boot/ovmx-distrib.img
ARCH=$(uname -m)

if [ ! -f "$DISTRIB_IMG" ]; then
    echo "FAIL: $DISTRIB_IMG is missing — the mastering stage did not run;"
    echo "      a stripped PID 1 cannot install a blank disk, so this test needs it."
    exit 1
fi

if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    QEMU=qemu-system-aarch64
    MACHINE="-machine virt -cpu cortex-a57"
    CONSOLE="console=ttyAMA0"
else
    QEMU=qemu-system-x86_64
    MACHINE=""
    CONSOLE="console=ttyS0"
fi

PASS=0
FAIL=0

record() {
    local desc="$1" rc="$2"
    if [ "$rc" -eq 0 ]; then
        echo "  PASS: $desc"; PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc"; FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# One case: pre-installed disk -> boot -> edit SYSUAF via AUTHORIZE from a
#           SYSTEM session -> reboot -> the system must come up with an identity.
# ---------------------------------------------------------------------------
# $2 = "up" (must boot) or "halt" (must fail-stop with the EXECINIT message).
# $3 = the UIC to stamp on the SYSTEM account, "g|m" in octal (vms-e60),
#      default "1|4". poisoned_uic passes a non-[1,4] UIC to prove the boot's
#      identity is the executive's constant, NOT whatever SYSUAF stores; every
#      other case leaves SYSTEM at [1,4]. This is the FILE CONTENT written, not
#      a claim about the identity the boot ends up with -- see the boot-2
#      "SYSTEM [1,4] established" assertion for why the two can differ.
run_case() {
    local tag="$1" expect="${2:-up}" uic="${3:-1|4}"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    echo "CASE $tag: AUTHORIZE MODIFY SYSTEM -> binary \$UAFDEF round-trip (UIC ${uic}), expect=$expect"
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    # vms-2213: OPA0: LOGINOUT waits for the operator RETURN before Username:; a
    # lone CR at t=0 is lost (serial not up yet), so feed one per second until
    # the prompt appears. Bounded.
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: install ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    # --- Provision: a real SYSTEM session edits the real SYSUAF ---
    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    # AUTHORIZE, the SUPPORTED SYSUAF editor, over the interactive terminal
    # (the "operator types at UAF>" shape run_norecord_case uses). MODIFY SYSTEM
    # keeps the account authorized while rewriting the binary $UAFDEF file
    # PROVISION actually reads on the next boot -- a genuine write->read
    # round-trip.
    #
    # This REPLACES an OPEN/WRITE of SYS$SYSTEM:SYSUAF.DAT, which is NOT a SYSUAF
    # edit and never was (run_norecord_case's header): OPEN/WRITE $CREATEs a
    # sequential TEXT version, and once the mastered system disk carries the
    # SYS$SPECIFIC per-root [SYS0.SYSEXE] directory (vms-f05) a create through
    # the SYS$SYSTEM: search list lands that text file in the PRIMARY member,
    # where it SHADOWS the binary indexed SYSUAF the common member holds. The
    # next boot's PROVISION opens the shadow, cannot bind it as Prolog-3, and
    # halts "no SYSTEM account" -- the very halt this rig exists to catch, fired
    # by the rig's own edit mechanism rather than by the account state under
    # test. It only "passed" before the SYS$SPECIFIC dirs existed because the
    # create then FAILED (RMS$_DNF, no primary-member directory) and the boot
    # read the untouched shipped binary. AUTHORIZE (like norecord's REMOVE,
    # vms-0a5/088e14bc) writes the real indexed file, so these positive cases
    # are once again true controls for the negative one.
    #
    # /UIC is octal (vms-e60), matching the "g|m" the case carries; poisoned_uic
    # names a non-[1,4] UIC to prove vms_kif_establish_system() constructs [1,4]
    # regardless of what SYSUAF stores.
    send 'RUN SYS$SYSTEM:AUTHORIZE.EXE'; sleep 3
    if waitfor 'UAF>' 30 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE starts (UAF> prompt)" "$rc"
    send "MODIFY SYSTEM/UIC=[${uic//|/,}]"; sleep 2
    send 'EXIT'; sleep 3              # EXIT triggers save_sysuaf -> binary write
    send 'SHOW TIME'; sleep 2         # back at DCL: a marker the RUN returned

    # The edit must have reported success AND been written back, or the rest of
    # the case is measuring nothing. (This replaces the old "TYPE shows the row"
    # check, which matched only the ECHO of the typed WRITE command, not a real
    # read-back of a persisted account.)
    if grep -qF '%UAF-S-MDFYMSG' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE reports the SYSTEM record modified" "$rc"
    if grep -qF '%UAF-I-SAVED' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE writes the binary SYSUAF back on exit" "$rc"

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: the boot that has to read what was written ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    if [ "$expect" = "halt" ]; then
        # NEGATIVE CONTROL. Proves this whole rig can still go RED, and proves
        # the fail-stop SURVIVED being moved out of PID 1 into PROVISION.EXE,
        # and then survived a second move (vms-a17e): identity establishment
        # no longer reads SYSUAF at all (vms_kif_establish_system() constructs
        # SYSTEM's identity as an executive constant regardless of what SYSUAF
        # contains), so this halt no longer comes from a failed identity read
        # -- it rides provision_home_directories()'s SYSUAF walk instead,
        # which is why the message changed from "no SYSTEM record" /
        # "the system process has no authorized identity" to the text below.
        # A fail-stop that was relocated and never fired again is a fail-stop
        # that was deleted (Rule 10: the condition is made unreachable, and it
        # only stays unreachable if entering it still stops the system).
        if waitfor '%OVMX-F-EXECINIT, no SYSTEM account' 120 "$log2"; then
            rc=0
        else
            rc=1
        fi
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
        record "$tag boot 2: HALTS with '%OVMX-F-EXECINIT, no SYSTEM account'" "$rc"

        if grep -qF '%OVMX-I-EXECINIT, no session could ever authenticate as SYSTEM' "$log2"; then
            rc=0
        else
            rc=1
        fi
        record "$tag boot 2: the detail line is PROVISION.EXE's SYSTEM-account continuity check" "$rc"

        # ...and it must NOT reach a login prompt. A system with no identity
        # that hands out a console is the exact thing the halt exists to stop.
        if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
        record "$tag boot 2: no login prompt on a system with no identity" "$rc"

        if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
        return
    fi

    wake_login "$log2"
    if waitfor 'Username:' 120 "$log2"; then rc=0; else rc=1; fi
    record "$tag boot 2: reaches the login prompt" "$rc"

    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # THE ASSERTION THE OPERATOR'S FAILURE WAS. Whole-log grep is safe: this is
    # a boot-time diagnostic printed before any prompt exists, so nothing this
    # script typed can have produced it.
    if grep -qF '%OVMX-F-EXECINIT, no SYSTEM account' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: NO '%OVMX-F-EXECINIT, no SYSTEM account' halt" "$rc"

    # And the positive half: an identity was actually established, with the
    # right values. Asserting only the absence of the halt would pass on a boot
    # that never got as far as trying.
    if grep -qF 'system identity SYSTEM [1,4] established by the executive' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: SYSTEM [1,4] established by the executive" "$rc"

    if [ "$rc" -ne 0 ] || grep -qF '%OVMX-F-EXECINIT' "$log2"; then
        echo "--- $tag boot 2 log ---"
        cat "$log2"
    fi
}

# ---------------------------------------------------------------------------
# NEGATIVE CONTROL 2: the startup process itself goes missing (vms-56c).
#
# PROVISION.EXE is boot-critical -- PID 1 stages it off the ODS-2 volume over
# the ACP and forks it as the startup process. If the image is absent the system
# has no way to acquire an identity, so PID 1 must FAIL-STOP -- never fall
# through to a login prompt on a system with no identity.
#
# vms-0a5: with DELETE now $ERASEing on the volume over the ACP (IO$_DELETE), the
# absent image is caught at boot-image staging (ovmx_init.c stage_boot_images(),
# SYSINIT) -- the earliest honest point, before the startup process is even
# forked -- and halts with the SYSINIT staging message. Asserting that specific
# message proves the mandatory-image staging guard fires and is not some other
# halt in disguise. (run_startup()'s later stat() guard remains the backstop for
# a staged copy that vanishes, and for the NetBSD-vax substrate that does not
# stage; it just is not the one that fires when the volume file is gone.)
#
# Injected THROUGH THE FILE, like every other case: a real SYSTEM session
# deletes the real image off the installed disk with DCL DELETE. No source is
# edited. If the delete did not land on the volume, boot 2 comes up and the halt
# assertion below fails -- so this case cannot false-pass.
#
# (The other fatal run_startup() path -- PROVISION.EXE activates but the
# executive REFUSES setident -- is caught by the same function at its waitpid
# nonzero-status branch, but is not injectable through the file from a session;
# it is left to inspection here rather than claimed as covered.)
# ---------------------------------------------------------------------------
run_provision_missing_case() {
    local tag="noprovision"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    echo "CASE $tag: SYSTEM deletes SYS\$SYSTEM:PROVISION.EXE, expect=halt"
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    # vms-2213: OPA0: LOGINOUT waits for the operator RETURN before Username:; a
    # lone CR at t=0 is lost (serial not up yet), so feed one per second until
    # the prompt appears. Bounded.
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: install, then delete the startup image off the disk ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    # An explicit version (here ;* = all versions) is REQUIRED on DELETE --
    # a bare "DELETE SYS$SYSTEM:PROVISION.EXE" is refused with
    # "%DELETE-E-DELVER, explicit version number or wild card required"
    # (authentic VMS, VSI OpenVMS DCL Dictionary, DELETE; landed in vms-1c6
    # #478). Without the ;* this delete never lands, PROVISION.EXE survives,
    # and boot 2 comes up instead of halting -- the exact false-negative this
    # case exists to catch.
    send 'DELETE/LOG SYS$SYSTEM:PROVISION.EXE;*'; sleep 2
    send 'DIRECTORY SYS$SYSTEM:PROVISION.EXE'; sleep 3

    # The delete must actually have landed, or boot 2 measures nothing. DELETE
    # /LOG prints the authentic '%DELETE-I-FILDEL, <spec> deleted' on success
    # (VSI OpenVMS DCL Dictionary, DELETE/LOG; vms-1c6 #478 corrected this from
    # the earlier non-authentic '%DELETE-S-DELETED'); a delete that found no
    # file prints '%RMS-E-FNF' / '%DELETE-W-SEARCHFAIL' instead and this check
    # goes red rather than silently measuring an intact disk.
    if grep -qiE '%DELETE-I-FILDEL|%DELETE-S-DELETED' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: PROVISION.EXE deleted off the disk" "$rc"

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: no startup image on disk -> PID 1 must fail-stop ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    # Whole-log grep is safe: a boot-time diagnostic printed before any prompt
    # exists, so nothing this script typed can have produced it.
    #
    # vms-0a5: DELETE now $ERASEs PROVISION.EXE off the ODS-2 VOLUME over the ACP
    # (IO$_DELETE), not a /vms passthrough copy the booted system never reads. So
    # the missing image is caught at the EARLIER, more honest point: PID 1 stages
    # the mandatory boot images off the volume over the ACP in SYSINIT
    # (stage_boot_images) BEFORE it ever forks the startup process, so the read
    # of the now-absent PROVISION.EXE fails there and fail-stops with the SYSINIT
    # staging halt rather than run_startup()'s later stat() guard. Both are honest
    # fail-stops before any login; landing the delete at the ACP layer is exactly
    # what moves the catch earlier.
    if waitfor '%OVMX-F-SYSINIT, boot-image staging failed' 120 "$log2"; then
        rc=0
    else
        rc=1
    fi
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
    record "$tag boot 2: HALTS at boot-image staging (PROVISION.EXE gone off the volume)" "$rc"

    if grep -qF 'SYS$SYSTEM:PROVISION.EXE could not be read from the ODS-2 volume over the ACP' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: the detail line names PROVISION.EXE unreadable over the ACP" "$rc"

    # ...and it must NOT reach a login prompt.
    if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: no login prompt on a system with no startup image" "$rc"

    if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
}

# ---------------------------------------------------------------------------
# NEGATIVE CONTROL: SYSUAF loses its SYSTEM account (vms-0a5).
#
# THE AUTHENTIC MECHANISM. SYSUAF.DAT is an RMS INDEXED file of binary $UAFDEF
# records, and the AUTHORIZE utility is the supported interface that removes an
# account from it -- it $DELETEs the record and writes the indexed file back
# (VSI OpenVMS Guide to System Security; AUTHORIZE). DCL OPEN/WRITE cannot edit
# SYSUAF: OPEN/WRITE CREATES A NEW SEQUENTIAL VERSION and never rewrites the
# indexed file LOGINOUT / PROVISION read, so an OPEN/WRITE "edit" of SYSUAF is
# not a VMS operation that persists to the account database. That is exactly why
# the write->read round-trip was never exercised before this item: the earlier
# form of this case wrote a sequential text version that the next boot's binary
# reader ($UAFDEF, ovmx_sysuaf_enum over the ACP) never read, so removing the
# SYSTEM row "in the file" changed nothing PROVISION saw and the system did not
# halt (the false pass this item closes).
#
# So this case mutates through AUTHORIZE: RUN SYS$SYSTEM:AUTHORIZE, REMOVE
# SYSTEM. On EXIT, AUTHORIZE authors a fresh versioned $UAFDEF indexed file over
# the Files-11 ODS-2 ACP (ovmx_sysuaf_write_all -> IO$_CREATE), which is EXACTLY
# the file PROVISION.EXE reads on the next boot (ovmx_sysuaf_enum over the same
# ACP). The removal therefore GENUINELY persists and is read back -- a real
# write->read round-trip, no executive-constant shortcut. With no SYSTEM row
# anywhere in SYSUAF, no session could ever authenticate as SYSTEM, so
# PROVISION.EXE fail-stops (provision_home_directories()'s account-provisioning
# walk recognises it never saw a SYSTEM row) and the system never reaches a
# login prompt.
# ---------------------------------------------------------------------------
run_norecord_case() {
    local tag="norecord"
    local disk="/tmp/e2e-$tag.img"
    local log1="/tmp/e2e-$tag-boot1.log"
    local log2="/tmp/e2e-$tag-boot2.log"
    local fifo="/tmp/e2e-$tag.in"
    local qp=""

    echo ""
    echo "=========================================================="
    echo "CASE $tag: AUTHORIZE REMOVE SYSTEM (binary indexed SYSUAF), expect=halt"
    echo "=========================================================="

    rm -f "$disk" "$log1" "$log2" "$fifo"
    cp "$DISTRIB_IMG" "$disk"
    mkfifo "$fifo"

    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log1" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    send() { printf '%s\r' "$1" >&4; }
    wake_login() {
        local logf="$1" w=0
        until grep -qaF 'Username:' "$logf" 2>/dev/null || [ "$w" -ge 120 ]; do
            send ''; sleep 1; w=$((w + 1))
        done
    }
    waitfor() {
        local pat="$1" lim="${2:-60}" log="$3" w=0
        while [ $w -lt $((lim * 4)) ]; do
            grep -qF "$pat" "$log" 2>/dev/null && return 0
            kill -0 "$qp" 2>/dev/null || return 1
            sleep 0.25; w=$((w + 1))
        done
        return 1
    }

    # --- Boot 1: log in as SYSTEM, REMOVE the SYSTEM account via AUTHORIZE ---
    wake_login "$log1"
    if waitfor 'Username:' 120 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: pre-installed disk boots and reaches the login prompt" "$rc"
    if [ "$rc" -ne 0 ]; then
        kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&-
        echo "--- boot 1 log ---"; cat "$log1"
        return
    fi

    send 'SYSTEM'; sleep 1
    send 'MANAGER'; sleep 3
    if waitfor 'Welcome to OpenVMX' 60 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: SYSTEM logs in" "$rc"

    # AUTHORIZE over the interactive terminal: a RUN'd image's SYS$INPUT is the
    # terminal here (not a procedure data block), so UAF> reads what we type.
    # This is the "operator types at UAF>" shape, which works interactively even
    # though it cannot work inside a command procedure (OVMX$INSTALL.COM's note).
    send 'RUN SYS$SYSTEM:AUTHORIZE.EXE'; sleep 3
    if waitfor 'UAF>' 30 "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE starts (UAF> prompt)" "$rc"
    send 'REMOVE SYSTEM'; sleep 2
    send 'Y'; sleep 2                 # confirm the REMOVE prompt
    send 'EXIT'; sleep 3              # EXIT triggers save_sysuaf -> binary write
    send 'SHOW TIME'; sleep 2         # back at DCL: a marker the RUN returned

    # The REMOVE and the on-exit binary write must both have reported success
    # in-session, or the rest of the case is measuring nothing.
    if grep -qF '%UAF-S-REMMSG' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE reports the SYSTEM record removed" "$rc"
    if grep -qF '%UAF-I-SAVED' "$log1"; then rc=0; else rc=1; fi
    record "$tag boot 1: AUTHORIZE writes the binary SYSUAF back on exit" "$rc"

    # See THE WRITEBACK TRAP at the top of this file.
    echo "  (settling ${SETTLE_SECS}s for guest writeback)"
    sleep "$SETTLE_SECS"
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null

    # --- Boot 2: PROVISION reads the binary SYSUAF; no SYSTEM row -> fail-stop ---
    rm -f "$fifo"; mkfifo "$fifo"
    # shellcheck disable=SC2086
    timeout "$BOOT_TIMEOUT" $QEMU $MACHINE \
        -kernel "$KERNEL" -initrd "$INITRD" \
        -nographic -append "$CONSOLE loglevel=3 quiet" \
        -m 512M -smp 1 -nic none -nodefaults -serial stdio \
        -drive file="$disk",format=raw,if=virtio,cache=writethrough \
        -no-reboot <"$fifo" >"$log2" 2>&1 &
    qp=$!
    exec 4>"$fifo"

    # Whole-log grep is safe: a boot-time diagnostic printed before any prompt
    # exists, so nothing this script typed can have produced it.
    if waitfor '%OVMX-F-EXECINIT, no SYSTEM account' 120 "$log2"; then rc=0; else rc=1; fi
    kill "$qp" 2>/dev/null; wait "$qp" 2>/dev/null; exec 4>&- 2>/dev/null
    record "$tag boot 2: HALTS with '%OVMX-F-EXECINIT, no SYSTEM account'" "$rc"

    if grep -qF '%OVMX-I-EXECINIT, no session could ever authenticate as SYSTEM' "$log2"; then
        rc=0
    else
        rc=1
    fi
    record "$tag boot 2: the detail line is PROVISION.EXE's SYSTEM-account continuity check" "$rc"

    # ...and it must NOT reach a login prompt. A system with no SYSTEM account
    # that hands out a console is the exact thing the halt exists to stop.
    if grep -qF 'Username:' "$log2"; then rc=1; else rc=0; fi
    record "$tag boot 2: no login prompt on a system with no SYSTEM account" "$rc"

    if [ "$FAIL" -ne 0 ]; then echo "--- $tag boot 2 log ---"; cat "$log2"; fi
}

echo "=== OVMX release e2e: boot -> provision -> boot (vms-9b7) ==="
echo "Architecture: $ARCH   QEMU: $QEMU"

# The three positive cases below were once the sixth-field-separator variants of
# the operator's original halt -- a 512-byte buffer in the SYSUAF TEXT parser.
# That parser is gone: PID 1 reads no SYSUAF, and PROVISION reads the BINARY
# $UAFDEF file, whose records are fixed-size, so a "separator position" no longer
# exists to vary. Each now runs an independent boot -> AUTHORIZE MODIFY SYSTEM ->
# boot round-trip against the live binary reader; retained as regression breadth
# and, together, the positive controls for the norecord/noprovision halts.
#
# (They previously "edited" SYSUAF with DCL OPEN/WRITE, which is not a SYSUAF
# edit -- see run_case's body and run_norecord_case's header for why that wrote
# a sequential text SHADOW that broke the next boot once the system disk gained
# its SYS$SPECIFIC per-root directory.)

# CONTROL 1 -- MODIFY the shipped SYSTEM account (UIC left at [1,4]). Proves the
# rig's edit mechanism writes a SYSUAF the next boot reads and comes up on.
run_case short up

# CONTROL 2 -- a second independent boot -> edit -> boot round-trip.
run_case inwin up

# CONTROL 3 -- a third independent boot -> edit -> boot round-trip.
run_case longrow up

# CASE (vms-a17e) -- THE ZERO-SYSUAF-READS-FOR-IDENTITY PROOF. AUTHORIZE stamps
# the SYSTEM account with a UIC that is NOT [1,4]. Before vms-a17e PROVISION.EXE
# read the UIC out of SYSUAF and handed it to VMS_IOCTL_SETIDENT, so the boot
# identity would have followed this field. After vms-a17e
# vms_kif_establish_system() takes no uic argument at all -- SYSTEM/[1,4]/ALL are
# vms.ko's own VMS_SYSTEM_UIC / VMS_PRV_M_SYSTEM_ALL constants (vms_internal.h)
# -- so the boot-2 "SYSTEM [1,4] established by the executive" assertion MUST
# still read [1,4], proving the stored UIC was never read to construct it.
#
# (A real INTERACTIVE SYSTEM/MANAGER login WOULD authenticate as the stored UIC
# -- LOGINOUT is SYSUAF's first reader, unmodified VMS behaviour -- but the boot
# process's identity, not the login session's, is this case's scope, so that is
# not probed here.) /UIC is octal (vms-e60); [50,50] is simply a value != [1,4].
run_case poisoned_uic up "50|50"

# NEGATIVE CONTROL. SYSUAF with NO SYSTEM row at all -- a condition VMS is never
# in, which OVMX therefore makes unreachable rather than handles (Rule 10). This
# must still stop the system, from its home in PROVISION.EXE. Without this case
# the four "up" cases above are all "did not halt" assertions with nothing
# showing they could ever have halted.
#
# vms-0a5: this case now removes the SYSTEM account through AUTHORIZE (which
# writes the binary indexed SYSUAF back over the ACP), the authentic mechanism,
# so the halt is driven by a write that GENUINELY persisted to the file
# PROVISION reads -- see run_norecord_case's header. The functional guarantee it
# proves -- no SYSTEM account means no login prompt, ever -- is unchanged; the
# path to it is now a real write->read round-trip rather than a text write the
# reader ignored.
run_norecord_case

# NEGATIVE CONTROL 2 (vms-56c, vms-0a5). The startup process image itself is
# deleted off the disk from a SYSTEM session -- over the ACP, so it leaves the
# ODS-2 volume, not just a passthrough copy. PID 1 must fail-stop at boot-image
# staging, proving the mandatory-image guard fires and that the boot-critical
# image is not a silently-skippable step.
run_provision_missing_case

echo ""
echo "=========================================="
echo "  RESULTS: $PASS passed, $FAIL failed"
echo "=========================================="
[ "$FAIL" -eq 0 ] || exit 1
echo "  ALL RELEASE E2E CHECKS PASSED"
