#!/usr/bin/env python3
"""comgen.py - a DCL semantic-oracle probe from a DCL spec (rd vms-8d1).

A DCL family (tools/oracle/semantic/specs-dcl/<family>.py) lists SETUP lines and
CASES of (CASE-ID, DCL expression). This writes SP_<FAMILY>.COM, which the real
OpenVMS node and OVMX both run with @: for each case it assigns the expression
to a symbol and prints

    <CASE-ID> st=<$STATUS hex> t=<F$TYPE of the result> v="<the result>"

between the "=== SEMPROBE <family> BEGIN/END ===" markers semantic_diff.py
reads -- the same transcript shape as a MACRO/C probe. An expression DCL
refuses leaves the symbol empty ("") and its error status in st (a SET NOON
before each case gives $STATUS a success value first, so st is this case's);
the message DCL prints for it is not a case line and is not compared.

  comgen.py <specs-dcl/family.py>      the .COM on stdout
"""
import os
import sys


def load(spec):
    g = {}
    exec(compile(open(spec).read(), spec, "exec"), g)
    return os.path.splitext(os.path.basename(spec))[0], g.get("SETUP", []), g["CASES"]


def gen(spec):
    fam, setup, cases = load(spec)
    seen = set()
    out = ["$! SP_%s.COM -- generated by tools/oracle/semantic/comgen.py from" % fam.upper(),
           "$! tools/oracle/semantic/specs-dcl/%s.py (rd vms-8d1). DO NOT EDIT." % fam,
           "$ SET NOON",
           '$ WRITE SYS$OUTPUT "=== SEMPROBE %s BEGIN ==="' % fam]
    for ln in setup:
        out.append("$ " + ln)
    for cid, expr in cases:
        assert cid not in seen, "duplicate case %s" % cid
        seen.add(cid)
        out.append('$ SP_V = ""')
        out.append("$ SET NOON")          # a command: $STATUS is its success
        out.append("$ SP_V = %s" % expr)
        out.append("$ SP_ST = $STATUS")
        out.append('$ WRITE SYS$OUTPUT "%s st=", F$FAO("!XL", F$INTEGER(SP_ST)), " t=", F$TYPE(SP_V), " v=""", SP_V, """"'
                   % cid)
    out.append('$ WRITE SYS$OUTPUT "=== SEMPROBE %s END ==="' % fam)
    out.append("$ EXIT")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(gen(sys.argv[1]))
