#!/bin/sh
# survey_x86_64_relocs.sh — empirical ground-truth survey of every ELF x86_64
# relocation type musl-gcc emits for OVMX's shareable/DCL source set, at the
# flags this project has standardized on for x86_64 (-fPIC -mtls-dialect=gnu2,
# per vms-be5's precedent — see src/imgact/test/run_test_x86_64.sh).
#
# Bead vms-680 (under vms-bdf, LINK.EXE x86_64 backend). This is grounding,
# not design: it cross-compiles the SAME object set vms-b65.1-.6 built for
# aarch64 (src/vmsprocess, src/libvms, src/vmsfs, src/vmslnm, src/vmsrms,
# src/vmsdcl) to x86_64 .o files and tallies every distinct ELF r_type by
# name and count, as observed by readelf -r — not hand-typed from memory.
#
# Usage:   tools/survey_x86_64_relocs.sh [--check]
#   (no args)  regenerate docs/design-link-x86_64-relocs.md from a fresh build
#   --check    regenerate into a temp file and diff against the committed doc;
#              nonzero exit + diff output if the ground truth has drifted
#              (this is what CI runs)
#
# Requires: musl-gcc, readelf (binutils). Both are already host tooling on the
# x86_64 dev host (CLAUDE.md: musl cross-compilation is build-tooling, not a
# runtime — Rule 9 is about the RUNTIME target, not the compiler).
set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
OUT_DOC="$REPO/docs/design-link-x86_64-relocs.md"

MODE=${1:-}

CC=${CC:-musl-gcc}
CFLAGS="-fPIC -O2 -mtls-dialect=gnu2 -c"

command -v "$CC" >/dev/null 2>&1 || { echo "survey_x86_64_relocs: $CC not found" >&2; exit 1; }
command -v readelf >/dev/null 2>&1 || { echo "survey_x86_64_relocs: readelf not found" >&2; exit 1; }

WORK=$(mktemp -d /tmp/survey-x86_64-relocs.XXXXXX)
trap 'rm -rf "$WORK"' EXIT

# The six components vms-b65.1-.6 migrated to the VMS-native toolchain for
# aarch64. Same source set, x86_64 target this time.
COMPONENTS="vmsprocess libvms vmsfs vmslnm vmsrms vmsdcl"

INCS=""
for c in $COMPONENTS vmslink; do
    [ -d "$REPO/src/$c/include" ] && INCS="$INCS -I$REPO/src/$c/include"
done
# src/libvmssys has no include/ subdir (headers live at its top level), so the
# loop above never picks it up. sys_uai.c (src/libvms/syssvc/sys_uai.c)
# #includes vms_kif.h from there — add it explicitly (vms-354, option b).
INCS="$INCS -I$REPO/src/libvmssys"

TALLY="$WORK/tally.txt"
: > "$TALLY"

BUILT_LOG="$WORK/built.txt"
FAILED_LOG="$WORK/failed.txt"
: > "$BUILT_LOG"
: > "$FAILED_LOG"

for c in $COMPONENTS; do
    SRCDIR="$REPO/src/$c"
    [ -d "$SRCDIR" ] || { echo "survey_x86_64_relocs: missing src dir $SRCDIR" >&2; exit 1; }
    find "$SRCDIR" -name '*.c' -not -path '*/test/*' | sort | while IFS= read -r f; do
        rel=${f#"$REPO"/}
        obj="$WORK/$(echo "$rel" | tr '/' '_').o"
        if $CC $CFLAGS $INCS -o "$obj" "$f" 2>"$WORK/err.log"; then
            echo "$rel" >> "$BUILT_LOG"
            # readelf -r columns: Offset Info Type Sym.Value Sym.Name[+Addend]
            # "Type" is field 3 in the RELA table rows (skip header lines).
            readelf -rW "$obj" 2>/dev/null | awk -v src="$rel" '
                /^Relocation section/ { next }
                /^  Offset/ { next }
                NF >= 4 && $1 ~ /^[0-9a-f]+$/ {
                    print $3 "\t" src
                }
            ' >> "$TALLY"
        else
            echo "$rel: $(tail -1 "$WORK/err.log")" >> "$FAILED_LOG"
        fi
    done
done

N_BUILT=$(wc -l < "$BUILT_LOG" | tr -d ' ')
N_FAILED=$(wc -l < "$FAILED_LOG" | tr -d ' ')

# Tally: distinct r_type -> count, and one example source object per type.
TYPES_SORTED="$WORK/types_sorted.txt"
sort "$TALLY" > "$TYPES_SORTED"

gen_doc() {
    DEST=$1
    {
        echo "# x86_64 Relocation Survey — LINK.EXE grounding (vms-680)"
        echo
        echo "**Generated by \`tools/survey_x86_64_relocs.sh\` — do not hand-edit.**"
        echo "Re-run the script to regenerate; \`tools/survey_x86_64_relocs.sh --check\`"
        echo "(wired into CI) diffs a fresh run against this file and reds if it drifts."
        echo
        echo "## Method"
        echo
        echo "Cross-compiled every non-test \`.c\` file in the vms-b65.1-.6 object set"
        echo "(\`src/vmsprocess\`, \`src/libvms\`, \`src/vmsfs\`, \`src/vmslnm\`, \`src/vmsrms\`,"
        echo "\`src/vmsdcl\`) to x86_64 \`.o\` files with:"
        echo
        echo '```'
        echo "$CC $CFLAGS -I<component>/include ..."
        echo '```'
        echo
        echo "(\`-fPIC -mtls-dialect=gnu2\`, per vms-be5's standing precedent for x86_64"
        echo "OVMX builds — see \`src/imgact/test/run_test_x86_64.sh\`.) Every produced"
        echo "\`.o\` was scanned with \`readelf -r\` and every distinct \`r_type\` name was"
        echo "tallied by occurrence count across the whole object set."
        echo
        echo "Files that failed to compile standalone (missing kernel/system headers"
        echo "outside this tree, multi-TU-only symbols, etc.) are excluded from the"
        echo "tally and listed below for transparency — they contribute no relocation"
        echo "data either way."
        echo
        echo "## Result: $N_BUILT objects built, $N_FAILED failed to compile standalone"
        echo
        echo "## Relocation types observed"
        echo
        echo "| r_type | count | distinct source objects | example source |"
        echo "|---|---|---|---|"
        if [ -s "$TYPES_SORTED" ]; then
            awk -F'\t' '{print $1}' "$TYPES_SORTED" | sort -u | while IFS= read -r t; do
                cnt=$(awk -F'\t' -v t="$t" '$1==t' "$TYPES_SORTED" | wc -l | tr -d ' ')
                nsrc=$(awk -F'\t' -v t="$t" '$1==t {print $2}' "$TYPES_SORTED" | sort -u | wc -l | tr -d ' ')
                ex=$(awk -F'\t' -v t="$t" '$1==t {print $2; exit}' "$TYPES_SORTED")
                echo "| $t | $cnt | $nsrc | $ex |"
            done
        else
            echo "| (none observed) | 0 | 0 | - |"
        fi
        echo
        echo "## Cross-reference: LINK.EXE's existing R_AARCH64_* switch"
        echo
        echo "\`src/vmslink/link.c\`'s relocation-apply switch (~lines 615-990) currently"
        echo "handles only \`R_AARCH64_*\` types. Mapping observed \`R_X86_64_*\` types to"
        echo "their ARM64 analog (or noting no analog exists) is the input the"
        echo "downstream x86_64 reloc-apply items (vms-8f5, vms-cd1, vms-2e4) implement"
        echo "against:"
        echo
        echo "Table covers only the r_type values the run above actually observed —"
        echo "no type is listed unless it appears in the tally with a nonzero count."
        echo
        echo "| R_X86_64_* (observed) | R_AARCH64_* analog in link.c | notes |"
        echo "|---|---|---|"
        echo "| R_X86_64_64 | R_AARCH64_ABS64 | direct analog — absolute 64-bit address, S+A |"
        echo "| R_X86_64_PC32 | R_AARCH64_PREL32 (partial) | 32-bit PC-relative, S+A-P; x86_64's workhorse call/jmp/lea-rip disp32 has no single ARM64 analog (ARM64 splits this across ADRP+ADD/LDR page-relocs) |"
        echo "| R_X86_64_PLT32 | R_AARCH64_CALL26 / JUMP26 (role analog only) | PC-relative PLT-routed call; ARM64's CALL26/JUMP26 play the equivalent linker role via a different encoding (26-bit imm vs 32-bit disp) |"
        echo "| R_X86_64_GOTPCREL | R_AARCH64_ADR_GOT_PAGE + LD64_GOT_LO12_NC (role analog only) | PC-relative GOT-entry load; ARM64 splits GOT access across two page/offset relocs, x86_64 does it in one PC32-class reloc |"
        echo "| R_X86_64_REX_GOTPCRELX | (no ARM64 analog) | x86_64 linker-relaxation variant of GOTPCREL (mov->lea when GOT slot provably unneeded); ARM64 has no equivalent relaxable-GOT-load reloc class |"
        echo "| R_X86_64_GOTPC32_TLSDESC | R_AARCH64_TLSDESC_ADR_PAGE21 (role analog only) | TLSDESC GOT-slot address computation (PC-relative GOT offset, first half of the x86_64 TLSDESC codegen pair); ARM64's ADR_PAGE21 plays the equivalent role via a page/offset split instead of a flat PC32 |"
        echo "| R_X86_64_TLSDESC_CALL | R_AARCH64_TLSDESC_CALL | direct analog — same TLSDESC model, project standardizes on \`-mtls-dialect=gnu2\` specifically to land here (2-reloc x86_64 GOTPC32_TLSDESC+TLSDESC_CALL pair) instead of the TLSGD/GD model \`-mtls-dialect=gnu\` (the default) would emit |"
        echo "| R_X86_64_DTPOFF32 | (no ARM64 analog observed in link.c) | module-relative offset of a TLS variable within its TLS block, filled as an absolute 32-bit constant and added to the TLSDESC resolver's returned TP-offset at runtime (observed: paired 1:1 with each __thread variable reference, immediately following a GOTPC32_TLSDESC/TLSDESC_CALL pair); ARM64's TLSDESC path encodes the equivalent module offset inside the GOT-slot resolver data itself (via TLSDESC_LD64_LO12/ADD_LO12), not as a separate static .o-file reloc against the operand |"
        echo
        echo "## Cross-reference: LINK.EXE (static, in .o files) vs IMGACT.EXE (load-time)"
        echo
        echo "\`src/imgact/imgact.c\`'s x86_64 arch handling (vms-913.11, arch/x86_64/) is"
        echo "LOAD-time: it walks the shareable image's \`DT_RELA\`/\`DT_JMPREL\` dynamic"
        echo "relocation tables at activation and applies \`R_X86_64_RELATIVE\`,"
        echo "\`R_X86_64_GLOB_DAT\`, \`R_X86_64_JUMP_SLOT\`, and \`R_X86_64_TLSDESC\` — the"
        echo "*dynamic* reloc set that exists because the image is a real ET_DYN ELF"
        echo "shareable being loaded into a process."
        echo
        echo "None of \`R_X86_64_RELATIVE\`, \`GLOB_DAT\`, or \`JUMP_SLOT\` appear in the"
        echo "static \`.o\`-file survey above — they are synthesized by the *linker*"
        echo "(GNU ld today; OVMX's own LINK.EXE going forward) when it builds the"
        echo "\`.dynamic\`/GOT/PLT sections, not emitted by the compiler into object"
        echo "files. \`R_X86_64_TLSDESC\` is the one type that appears in BOTH: as a"
        echo "static \`.o\`-file reloc (compiler-emitted, link-time — LINK.EXE's job) AND"
        echo "as a load-time \`DT_RELA\` entry pointing at the TLSDESC GOT slot"
        echo "(IMGACT's job) — LINK.EXE resolves the compile-time TLSDESC relocation"
        echo "into a GOT-slot-producing form, and IMGACT resolves that GOT slot's"
        echo "dynamic entry at activation. The two jobs are sequential stages on the"
        echo "same symbol, not overlapping responsibility for the same event."
        echo
        echo "**Confirmed: LINK.EXE's job (this survey) and IMGACT's job (load-time"
        echo "DT_* relocs, already handled per vms-913.11) are not the same set.**"
        echo
        echo "## Objects that failed to compile standalone ($N_FAILED)"
        echo
        if [ -s "$FAILED_LOG" ]; then
            echo '```'
            sort "$FAILED_LOG"
            echo '```'
        else
            echo "(none — every non-test .c file in the object set compiled standalone)"
        fi
    } > "$DEST"
}

if [ "$MODE" = "--check" ]; then
    TMP_DOC="$WORK/check_doc.md"
    gen_doc "$TMP_DOC"
    if ! diff -u "$OUT_DOC" "$TMP_DOC"; then
        echo "survey_x86_64_relocs: committed $OUT_DOC is STALE — re-run tools/survey_x86_64_relocs.sh and commit" >&2
        exit 1
    fi
    echo "survey_x86_64_relocs: $OUT_DOC matches a fresh survey ($N_BUILT built, $N_FAILED failed)"
else
    gen_doc "$OUT_DOC"
    echo "survey_x86_64_relocs: wrote $OUT_DOC ($N_BUILT built, $N_FAILED failed)"
fi
