#!/usr/bin/env python3
"""no-new-hand-copies guard (INV-LEDGER, vms-8465).

INV-LEDGER forbids a SECOND, hand-maintained copy of a surface that already has
one authoritative source + generator (roadmap/milestones -> rd; releases -> git
tags; compat -> docs/compat/*.yaml). Every re-appearance of such a list in a
hand-edited doc is a fresh "standard N+1" seam (xkcd 927). This guard catches the
two highest-signal, ZERO-false-positive re-appearances, plus a small, documented,
extensible denylist of demoted phrasings.

WHAT IT CATCHES
    A. The compat generator marker line -- the provenance stamp emitted by
       render_compat.py -- appearing in any tracked doc OTHER than the one
       sanctioned generated file docs/compatibility-surface.md. (A copied compat
       table carries this marker.)
    B. The roadmap GENERATED:BEGIN marker appearing in any tracked doc OTHER than
       the one sanctioned generated file docs/release-roadmap-to-1.0.md. (A copied
       roadmap status block carries this marker.)
    C. A curated denylist of demoted hand-list phrasings (the "static for now"
       release list, "hand-maintained roadmap", etc.). Extend DENYLIST as new
       hand-copy patterns are demoted; keep every entry specific (low false
       positive).

Scope: tracked *.md docs (docs/**, README.md, root *.md). The generator SOURCES
under tools/ are excluded -- they legitimately contain the marker string
literals. Exit 0 = clean; non-zero = a hand-copy seam was found.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

# Marker -> the ONE file that is allowed to carry it (the sanctioned generated view).
SANCTIONED_MARKERS = {
    "GENERATED by tools/compat/render_compat.py": "docs/compatibility-surface.md",
    "GENERATED:BEGIN roadmap-reconcile": "docs/release-roadmap-to-1.0.md",
}

# Demoted hand-list phrasings. Each is a specific, high-signal regex -- a NEW one
# creeping into a doc means a parallel ledger is being hand-kept. Keep specific.
DENYLIST = [
    r"static\s+for\s+now.{0,40}release",          # the old landing-page release list
    r"hand[- ]maintained\s+(roadmap|release|milestone)",
    r"<!--\s*HAND-MAINTAINED-LEDGER\s*-->",        # explicit sentinel (tests + humans)
]

DENY_RE = re.compile("|".join(f"(?:{p})" for p in DENYLIST), re.I)


def tracked_md() -> list[str]:
    out = subprocess.run(
        ["git", "-C", REPO, "ls-files", "*.md", "docs/**/*.md"],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    return sorted(set(out))


def main() -> int:
    violations: list[str] = []
    for rel in tracked_md():
        path = os.path.join(REPO, rel)
        try:
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
        except (OSError, UnicodeDecodeError):
            continue
        for marker, sanctioned in SANCTIONED_MARKERS.items():
            if marker in text and rel != sanctioned:
                violations.append(
                    f"{rel}: carries the generated-surface marker "
                    f"'{marker}', which may ONLY appear in {sanctioned}. "
                    f"This is a hand-copy of a generated view.")
        for m in DENY_RE.finditer(text):
            line = text.count("\n", 0, m.start()) + 1
            violations.append(
                f"{rel}:{line}: demoted hand-list phrasing "
                f"'{m.group(0).strip()}' -- point at the source/generated view "
                f"instead of hand-maintaining a copy.")

    if violations:
        print("NO-NEW-HAND-COPIES: parallel-ledger seam(s) found (INV-LEDGER, "
              "vms-8465):", file=sys.stderr)
        for v in violations:
            print(f"  - {v}", file=sys.stderr)
        print("\nFix the SOURCE + its generator, then reference the generated "
              "view -- never hand-maintain a second copy.", file=sys.stderr)
        return 1

    print(f"clean: no new hand-maintained ledger copies "
          f"({len(tracked_md())} tracked docs scanned).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
